### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by simpleapples** [1c7/chinese-independent-developer#1]
#### simpleapples - [Github](https://github.com/simpleapples)
* :white_check_mark: [饭斯基](https://github.com/simpleapples/fansky): 第三方饭否iOS客户端
* :white_check_mark: [摇摇选餐](https://github.com/simpleapples/ShakeChoose): 随机选餐工具
* :white_check_mark: [AppStore全部作品](https://itunes.apple.com/cn/developer/zhiya-zang/id549139622)
* :white_check_mark: [PyBlockchainCLI](https://github.com/simpleapples/py-blockchain-cli): Python区块链命令行界面
* :white_check_mark: [短网址二维码生成器](https://github.com/simpleapples/url2qrcode): Chrome短网址二维码生成器

**Comment by 1c7** [comment]
OK，收到！感谢提交~！

**Comment by 1c7** [comment]
我把这个 issue 关掉~

**Comment by simpleapples** [comment]
多谢~

**Comment by 1c7** [comment]
@simpleapples  我稍微改了一下，删掉了 Python区块链命令行界面
因为列表里只能是网站 / App，不能有针对开发者的工具
（因为如果这样，那范围就太广了，Github 上超多人都可以提交，整个表会爆炸的）
希望理解。
~我休息去了，很晚了。晚安

**Comment by simpleapples** [comment]
理解 辛苦啦~
