### ISSUE TITLE
app store 搜索"boyang yu"

### ISSUE THREAD

**Issue by YBYHunter** [1c7/chinese-independent-developer#12]
这里面都是我业余时间写的一些工具类app，比较简单...如果大神感觉还行我开源也可以。

**Comment by 1c7** [comment]
稍等，我看到了你的  issue，但是现在太多人提交了，我要逐个处理~ 可能会慢一点，希望理解

**Comment by 1c7** [comment]
我临时 closed 一下，待会回来处理，我希望把 issue 这里弄整洁点

**Comment by 1c7** [comment]
Hello, 能麻烦你把想展示的项目根据如下格式填一下吗？

格式如下：
```
#### 名字 - [Github]()
* :white_check_mark: [网站/App名]()：一句话说明(尽量保持在一行内) - [更多介绍]()
```

如果你的项目还在开发，或者已经关闭了，可以用：
```
:clock8:
:x:
```

已关闭的项目最好附上一个更多介绍，里面讲解为什么关闭了，学到了什么

**Comment by 1c7** [comment]
https://itunes.apple.com/tm/developer/boyang-yu/id945625220?mt=8

**Comment by 1c7** [comment]
因为我不确定你是否想全部展示，而且你需要写中文的一句话介绍（这个我没法代劳）
