### ISSUE TITLE
为什么不接受我的pull request

### ISSUE THREAD

**Issue by andyesfly** [1c7/chinese-independent-developer#131]
#### dipiper财经数据接口 - [Github](https://github.com/andyesfly/dipiper)
* :clock8: [dipiper](http://dipiper.tech)这是一个基于nodejs的开源的财经数据接口包，为nodejs实现量化投资提供数据来源

**Comment by 1c7** [comment]
第一次的时候就已经接受了。后面没有必要重复发送
![image](https://user-images.githubusercontent.com/1804755/60864747-0f0ee680-a257-11e9-8132-c667af1ba5aa.png)
![image](https://user-images.githubusercontent.com/1804755/60864755-133b0400-a257-11e9-86b3-f1e4ee7b7ef6.png)
![image](https://user-images.githubusercontent.com/1804755/60864767-17672180-a257-11e9-8f8b-92f2fb3d2586.png)
![image](https://user-images.githubusercontent.com/1804755/60864772-1afaa880-a257-11e9-8056-b2c02a4ae468.png)
![image](https://user-images.githubusercontent.com/1804755/60864776-1df59900-a257-11e9-9b8b-b7c4fb6bc9b4.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/60864935-83498a00-a257-11e9-934a-93a5f8955985.png)

**Comment by wsdjeg** [comment]
这样的 spam 不 block？ 连续收到七八封邮件全是这个

---

wsdjeg

-------- 原始邮件 --------
主题：Re: [1c7/chinese-independent-developer] 为什么不接受我的pull request (#131)
发件人：Cheng Zheng
收件人：1c7/chinese-independent-developer
抄送：Subscribed


Closed #131<https://github.com/1c7/chinese-independent-developer/issues/131>.

―

**Comment by SaigyoujiYuyuko233** [comment]
![image](https://user-images.githubusercontent.com/39913604/60875696-f9a4b700-a26c-11e9-9551-40f97c979444.png)
awsl

**Comment by 1c7** [comment]
@wsdjeg @SaigyoujiYuyuko233 不好意思打扰到两位了。
我不知道怎么 block。我没试过 block user 是不是能阻止 PR 或者提 Issue。
上面的 QQ 聊天记录可以看到问题已经解决了。
如果下次碰到类似的情况我试试 block
