### ISSUE TITLE
申请收录：微信小程序-数独之光

### ISSUE THREAD

**Issue by maxwellyue** [1c7/chinese-independent-developer#137]
```
#### Maxwell
* :white_check_mark: [微信小程序-数独之光](https://www.jianshu.com/p/7a9e970dab2a)：经典益智数字游戏数独-[扫码试玩](https://upload-images.jianshu.io/upload_images/18082878-6f6aeebf5f55fc69.png?imageMogr2/auto-orient/strip|imageView2/2/w/1200/format/webp) 
```

**Comment by 1c7** [comment]
看了下没啥问题，我加进去，我把格式稍微调整一下：

#### Maxwell
* :white_check_mark: [微信小程序-数独之光](https://www.jianshu.com/p/7a9e970dab2a)：经典益智数字游戏数独

之所以去掉了小程序的扫码图片，是因为我发现如果点击跳转到 jianshu.io 
https://upload-images.jianshu.io/upload_images/18082878-6f6aeebf5f55fc69.png?imageMogr2/auto-orient/strip|imageView2/2/w/1200/format/webp

这个链接会报错 403，但是直接访问是没有问题的

**Comment by 1c7** [comment]
已加，close
