### ISSUE TITLE
有一些项目已经打不开了，甚至有跳转到菠菜网站的

### ISSUE THREAD

**Issue by igoing** [1c7/chinese-independent-developer#140]
言说：网站无法打开
声音笔记+的`更多介绍`，随机跳转菠菜网站
煎蛋：链接跳转Google play后找不到资源
Time Progress：Page not found

**Comment by 1c7** [comment]
收到，会逐个处理，谢告知

**Comment by 1c7** [comment]
完成
https://github.com/1c7/chinese-independent-developer/commit/c518a4d510218c6129636c6f0f67244c6ddd7bf3
