### ISSUE TITLE
#### 周利刚(杭州)

### ISSUE THREAD

**Issue by qq475742653** [1c7/chinese-independent-developer#142]
* :white_check_mark: [足迹中国](https://apps.apple.com/cn/app/id1482250279)：用地图截图记录你去过的中国的省市(上架不久,完善中)   
   --我也做了一个，你看我的网站www.headset.xin 
* :white_check_mark: [假装来电](https://apps.apple.com/cn/app/id1475866564)：设置一定时间后,收到虚假的来电,用于逃离某些场合
 ---这个我也做了一个，只是安卓的，自己用，没放出来。

**Comment by 1c7** [comment]
……emm？所以你想让我怎么做？
