### ISSUE TITLE
iBlockly

### ISSUE THREAD

**Issue by albuer** [1c7/chinese-independent-developer#143]
#### Albuer(FuZhou) - [Github](https://github.com/albuer)
* :white_check_mark: [iBlockly](https://github.com/albuer/iBlockly)：一款基于google blockly的积木编程软件

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/68993307-8ca3cc80-08b1-11ea-8551-9e7bedf20718.png)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/68993346-f1f7bd80-08b1-11ea-8d61-076730c7f4f0.png)

# 下载地址呢？
