### ISSUE TITLE
一撮毛 - 全网最牛自淘返现工具

### ISSUE THREAD

**Issue by zoumorn** [1c7/chinese-independent-developer#145]
### 一撮毛 - 全网最牛自淘返现工具 - [Github](https://github.com/zoumorn/tkreborn)
* :white_check_mark: [一撮毛]()：全网最牛自淘返现工具 - [更多介绍](https://github.com/zoumorn/tkreborn)

**Comment by 1c7** [comment]
你写的这个格式不对，我改了下，正确格式如下    

#### zoumorn - [Github](https://github.com/zoumorn)  
* :white_check_mark: [一撮毛](https://github.com/zoumorn/tkreborn)：全网最牛自淘返现工具

我检查一下内容，没问题就加进去

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/69699542-245fb100-1123-11ea-9c6d-de736a4f8f9c.png)

![image](https://user-images.githubusercontent.com/1804755/69699517-127e0e00-1123-11ea-98d9-3675186cd3b7.png)
![image](https://user-images.githubusercontent.com/1804755/69699532-1dd13980-1123-11ea-8d1e-98fd73c1a14e.png)
由于我是 mac 测试不了就算了
![image](https://user-images.githubusercontent.com/1804755/69699581-3ccfcb80-1123-11ea-97b5-3cb096b15c29.png)
看起来是没什么问题的，虽然我不太懂这个返现原理是什么
我先加进去

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/69703955-79082980-112d-11ea-8f61-1d7b39cf2e12.png)

**Comment by zoumorn** [comment]
thanks! 目前仅支持windows平台。

返现是：卖家设置的淘宝推广，推广人生产链接，买家通过推广的链接成交后，推广人获得佣金。
一撮毛：就是自动的推广。
