### ISSUE TITLE
#### 刷脸考勤系统 -[Github](https://github.com/inspurer/WorkAttendanceSystem)

### ISSUE THREAD

**Issue by inspurer** [1c7/chinese-independent-developer#146]
格式如下：
```
#### 名字 - [Github]()
* :white_check_mark: [网站/App名]()：一句话说明(尽量保持在一行内) - [更多介绍]()
```

如果你的项目还在开发，或者已经关闭了，可以用：
```
:clock8:
:x:
```

已关闭的项目最好附上一个更多介绍，里面讲解为什么关闭了，学到了什么

**Comment by inspurer** [comment]
#### 刷脸考勤系统 -[Github](https://github.com/inspurer/WorkAttendanceSystem)

基于 dlib 和 opencv 的 pc 端刷脸考勤系统

**Comment by 1c7** [comment]
收到，看了下 readme 没啥问题，我加进去

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/70202878-07943080-1756-11ea-8ea1-93fe48625b05.png)
已加到[程序员版面](https://github.com/1c7/chinese-independent-developer/blob/master/README-Programmer-Edition.md)
感谢提交

**Comment by inspurer** [comment]
多谢

发送自 Windows 10 版邮件应用

发件人: Cheng Zheng
发送时间: 2019年12月5日 11:52
收件人: 1c7/chinese-independent-developer
抄送: 月小水长; Author
主题: Re: [1c7/chinese-independent-developer] #### 刷脸考勤系统 -[Github](https://github.com/inspurer/WorkAttendanceSystem) (#146)

收到，看了下 readme 没啥问题，我加进去
