### ISSUE TITLE
申请加入我的项目

### ISSUE THREAD

**Issue by hellobanny** [1c7/chinese-independent-developer#148]
```
Banny(杭州) - [Github](https://github.com/hellobanny)
✅ 我的小目标：个人积分管理软件，督促用户成为更好的自己 - [更多介绍](https://apps.apple.com/cn/app/id1051212505)
✅ 红色工具箱：多个创意实用小工具集合，如肌肉启动，截屏记事，指尖轮盘等 - [更多介绍](https://apps.apple.com/cn/app/id1473577627)
```

**Comment by 1c7** [comment]
get ，我看一眼

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/70972924-8470c400-20df-11ea-8fac-0bbe8b289d84.png)

![image](https://user-images.githubusercontent.com/1804755/70972975-9f433880-20df-11ea-8163-7f4f967a2e1c.png)

看了下网址没啥问题，只是你这个格式我要改改再加进去：


#### Banny(杭州) - [Github](https://github.com/hellobanny)
* :white_check_mark: [我的小目标](https://apps.apple.com/cn/app/id1051212505)：个人积分管理软件，督促用户成为更好的自己
* :white_check_mark: [红色工具箱](https://apps.apple.com/cn/app/id1473577627)：多个创意实用小工具集合，如肌肉启动，截屏记事，指尖轮盘等
