### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by huifer** [1c7/chinese-independent-developer#154]
格式如下：
```
#### huifer(杭州) - [Github](https://github.com/huifer)
- ✅ 平面算法: 平面几何算法 - [更多介绍](https://github.com/huifer/planar_algorithm)
```

**Comment by 1c7** [comment]
好的

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/75885236-2099a400-5e61-11ea-9b86-7abf7c49b754.png)
https://github.com/1c7/chinese-independent-developer/blob/master/README-Programmer-Edition.md

已添加至程序员版面
