### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by tobyglei** [1c7/chinese-independent-developer#155]
#### tobyglei - [Github](https://github.com/tobyglei)
* :white_check_mark: [21云盒子](https://www.21yunbox.com)：最容易使用的云 - 自动化你的工作流程
**21云盒子**是代码构建，静态网页，Web应用发布，
云数据库托管，SSL证书生成和维护，极速CDN，
私有网络的一站式服务平台。

* :white_check_mark: [BlinkMath](https://apps.apple.com/au/app/blinkmath/id1497540228?l=en)：iOS app，累了眨眨眼，动动脑!

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/77630573-3f81e680-6f86-11ea-9711-ea44c4e5d47a.png)

![image](https://user-images.githubusercontent.com/1804755/77630592-46a8f480-6f86-11ea-9649-45126c1472f4.png)

看了下没啥问题，我加进去，感谢提交

**Comment by 1c7** [comment]
已加
![image](https://user-images.githubusercontent.com/1804755/77635702-ecac2d00-6f8d-11ea-8d7f-59a606ae983a.png)
