### ISSUE TITLE
程序员申请添加 微内核框架 tiny

### ISSUE THREAD

**Issue by xnat9** [1c7/chinese-independent-developer#187]
#### xnat9(成都) - [Github](https://github.com/xnat9)
* :white_check_mark: [tiny](https://github.com/xnat9/tiny)：小巧的java应用微内核框架, 可用于构建小工具项目，web项目，各种大大小小的项目

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/140596048-c3b95d89-4365-4bff-8dbd-175e6bed2b15.png)

**Comment by 1c7** [comment]
已加，感谢
