### ISSUE TITLE
[telegram] 中国独立开发者项目-交流群

### ISSUE THREAD

**Issue by 1c7** [1c7/chinese-independent-developer#19]
提交项目的时候有人提议建微信群，所以建了一个：
![mmqrcode1521431291484](https://user-images.githubusercontent.com/1804755/37577371-c31bac48-2b6c-11e8-81e6-e27ccd9fa22e.png)
这个群的目的是讨论独立开发，请不要闲聊

**Comment by 1c7** [comment]
虽然我担心群会变得很吵，然后只有前几天活跃，然后后面又变成了发广告的死群（没人说话）
但是仔细想了下，好像所有群最后差不多都是这样，所以就干脆建了群，反正也没什么坏处。
总之，希望大家能互相交流学习。请勿闲扯（可以去  v2ex 什么的。。）

**Comment by 1c7** [comment]
群里有人说的好『telegram或qq群都行，一般微信群肯定都是关掉提醒的，干扰太大，其次没有历史，二维码很快就失效了』

所以很快会换成  QQ 或者 telegram。现在微信先顶着用。

**Comment by 1c7** [comment]
Telegram：
https://t.me/joinchat/GekdRhLA2z3xCvptnybWZA

**Comment by 1c7** [comment]
注：目前保留微信群，毕竟不是每个人都用 Telegram

**Comment by 1c7** [comment]
## 结论：
各位请选择微信 / Telegram 加入，或者2个都加入。
主要考虑到不是每个人都用 Telegram。
而 QQ 群和微信群功能基本重合，就不建 QQ 群了。

**Comment by wsdjeg** [comment]
@1c7 微信群上线是 500 人，而且微信群没有群助手，新消息容易打扰到正在上班的用户，此外，微信群即便是设置了免打扰，来消息了，群还是会前置，严重影响上班需要用微信的用户。

有机会还是搞个 QQ 群吧，有空的人自然会来聊，忙起来了，QQ 群消息也不会干扰到用户。

**Comment by 1c7** [comment]
噢……
@wsdjeg  有道理，好，我建一个。

**Comment by 1c7** [comment]
@wsdjeg 建了个 QQ 群 678722344~ 
感谢提议

**Comment by abubuker** [comment]
Thanks For You

**Comment by leon332157** [comment]
@1c7 你所有commit都是在 :octocat: 上完成的？

**Comment by leon332157** [comment]
@1c7 其实如果用git的话放两个repo也没那么麻烦

**Comment by 1c7** [comment]
@1c7 嗯我直接在网页端完成编辑

**Comment by leon332157** [comment]
@1c7 但是我觉得放在码云的话，国内可能有更多人看到。在merge PR的时候，直接git同时push到两个repo就行了。我就觉得这个需要有更多人来加入，并且不再是人工加入，最好写个脚本什么的 😮

**Comment by leon332157** [comment]
像大的repo都是有机器人完成的，都是自动.

**Comment by 1c7** [comment]
@leon332157 可以诶，自动就行（解决了懒的问题）我看看咋整，
或者你有没有什么操作指南之类的，里面直接列出来跑命令 A B C D 就能搞定的？
我这几天看看吧，今天得先干活，现在12：20吃完饭了下午先干活。

把人工加入改成自动脚本加入这里有个问题，还是需要人工来审核质量。
我拒了不少提交来着（还好大家都比较 nice 没有直接骂我）
改成自动的话其实工作量并没有显著减少

**Comment by leon332157** [comment]
@1c7 审核的话好像是个问题...

**Comment by leon332157** [comment]
@1c7 可以这样，专门搞一些关键字，然后脚本，开个新的branch专门放需要审核的

**Comment by leon332157** [comment]
@1c7 http://pygithub.readthedocs.io/en/latest/introduction.html
看了看api，正好写python，缺点就是可能不够准确。。

**Comment by 1c7** [comment]
@leon332157 算了就不过度优化了，branch 什么的不弄了，不在这个上面花太多时间 
（我有好多好多其他事情要忙 = = ）
我把码云同步的事情看看，如果能简单就搞好，那我就搭起来，
然后依然是管 Github 这边，码云那边让它自动同步，我只是就隔阵子上去看看
总之多谢建议~~

**Comment by 1c7** [comment]
@leon332157  嗯~

**Comment by leon332157** [comment]
@1c7 嗯嗯

**Comment by leon332157** [comment]
@1c7 嗯嗯

**Comment by leon332157** [comment]
@1c7 https://www.zhihu.com/question/265657068 这是你需要在git上做的，我再找一下merge pr的文档，之后看看帮你写个脚本，这样你直接电脑里merge 和 push就行了

**Comment by leon332157** [comment]
https://github.com/leon332157/help_1c7

**Comment by leon332157** [comment]
这里的commit都是我用我的脚本做的 😄 :octocat:

**Comment by leon332157** [comment]
@1c7 现在就差主脚本和实际测试了

**Comment by 1c7** [comment]
@leon332157 好

**Comment by 1c7** [comment]
@leon332157 https://gitee.com/1c7/chinese-independent-developer
还在弄

**Comment by 1c7** [comment]
有个问题是，码云以 README-en 为标准来显示，而 github 这边显示 README，不确定咋处理比较好

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/38007291-52bf8f6c-327b-11e8-9db4-1a87a72f68d0.png)
http://git.mydoc.io/?t=223172 找到说明了

**Comment by leon332157** [comment]
@1c7 这个问题不大，我只需要开两个文件夹然后我复制完重命名就行了

**Comment by leon332157** [comment]
@1c7 我的git可以独立设置本地repo

**Comment by 1c7** [comment]
@leon332157 嗯，那个脚本就不费你时间继续写了，~ 我自己来弄吧。
其实就这样简单弄弄就行了，花这些时间有点阵仗太大的感觉

**Comment by leon332157** [comment]
@1c7 没事，这个模块你自己看看，我觉得还是很简单的，其实我也没啥事，闲的时候也没事干

**Comment by leon332157** [comment]
@1c7 差不多目录结构是这样：
home/github:
    /.git
    /README.md
home/gitee:
    /.git
   shutil.copy:
    /README.md --> README-en.md (os.rename)

**Comment by 1c7** [comment]
@leon332157  
https://gitee.com/1c7/chinese-independent-developer

OK，反正库现在已经有了就先告一段落~

**Comment by leon332157** [comment]
嗯嗯

**Comment by leon332157** [comment]
@1c7 我突然发现这个东西.
https://lindexi.gitee.io/lindexi/post/git%E9%95%9C%E5%83%8F%E4%BB%93%E5%BA%93.html

**Comment by leon332157** [comment]
https://www.jianshu.com/p/155886f9a838

**Comment by leon332157** [comment]
没想到git已经有镜像了。

**Comment by leon332157** [comment]
@1c7 那就不用脚本了，你是win的话，设置任务计划每次登陆都git remote update一下 :octocat:

**Comment by 1c7** [comment]
嗯

**Comment by 1c7** [comment]
好~

**Comment by leon332157** [comment]
@1c7 https://segmentfault.com/q/1010000006816225 参考这个，这个非常清楚

**Comment by 1c7** [comment]
我先 closed 掉这个  issue，因为太长了，另开一个，然后里面放加群的信息

**Comment by leon332157** [comment]
嗯
