### ISSUE TITLE
iOS 端 HTTPS 抓包分析工具 - Thor 

### ISSUE THREAD

**Issue by dake** [1c7/chinese-independent-developer#20]
这个可以加吗？
地址如下：
https://github.com/PixelCyber/Thor/blob/master/README-zh-Hans.md

**Comment by 1c7** [comment]
仔细看了下，是个抓包工具，针对开发者的。所以不收录了，感谢提交！
（请理解，因为 Github 上太多开发者工具了，如果都收录，这个表会炸的，表里面只能收录面对普通消费者的产品，比如一个换壁纸的 App，一个比价的  Chrome 扩展。等等。）

**Comment by 1c7** [comment]
感谢提交！
