### ISSUE TITLE
Quest新标签页

### ISSUE THREAD

**Issue by CarsonLam** [1c7/chinese-independent-developer#202]
#### Carson（广州） - [Github](https://github.com/CarsonLam)
* :white_check_mark: [Quest新标签页](https://support.qq.com/products/308410/blog/744528)：一款【聚合搜索】新标签页效率插件。

**Comment by 1c7** [comment]
好的收到，我稍后会加入到列表里。

**Comment by 1c7** [comment]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1804755/171990648-4d90d013-4625-45fc-9d9a-a2086752897e.png">

<img width="1204" alt="image" src="https://user-images.githubusercontent.com/1804755/171990655-ec9d31f3-4d16-4d22-b648-0a81ac2696a5.png">

<img width="946" alt="image" src="https://user-images.githubusercontent.com/1804755/171990693-0379dca9-5c43-4271-bd82-667bcbcc5b05.png">

**Comment by 1c7** [comment]
已加~ 感谢提交

**Comment by CarsonLam** [comment]
谢谢



Sent&nbsp;from&nbsp;my&nbsp;iPhone


------------------ 原始邮件 ------------------
发件人: Cheng Zheng ***@***.***&gt;
发送时间: 2022年6月4日 16:06
收件人: 1c7/chinese-independent-developer ***@***.***&gt;
抄送: Carson ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [1c7/chinese-independent-developer] Quest新标签页 (Issue #202)






已加~ 感谢提交
