### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by SpongeBobSun** [1c7/chinese-independent-developer#21]
Puff 密码管理器
Android: https://github.com/PuffOpenSource/Puff-Android
iOS: https://github.com/PuffOpenSource/Puff-iOS

Prodigal 音乐播放器
Android: https://github.com/SpongeBobSun/Prodigal
iOS: https://github.com/SpongeBobSun/Prodigal-iOS

🙏

**Comment by 1c7** [comment]
稍等，我看到了，我仔细看看你这个

**Comment by SpongeBobSun** [comment]
谢谢

**Comment by 1c7** [comment]
临时 close 一下，我知道上一条评论是一个小时前的，我也不知道时间为啥这么快，我在焦头烂额到处处理来着。待会我会回来处理你这个，今天内肯定搞定！
感谢提交哈！

**Comment by 1c7** [comment]
能麻烦你用如下格式填一下吗？谢谢！

格式如下：
```
#### 名字 - [Github]()
* :white_check_mark: [网站/App名]()：一句话说明(尽量保持在一行内) - [更多介绍]()
```

如果你的项目还在开发，或者已经关闭了，可以用：
```
:clock8:
:x:
```

已关闭的项目最好附上一个更多介绍，里面讲解为什么关闭了，学到了什么

**Comment by 1c7** [comment]
因为项目需要一句话介绍，这个介绍我没法代劳帮你写上

**Comment by 1c7** [comment]
感谢提交！

**Comment by SpongeBobSun** [comment]
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://github.com/PuffOpenSource)：开源免费的离线密码管理器 - [iOS](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8) [Android](https://play.google.com/store/apps/details?id=sun.bob.leela)

* :white_check_mark: [Prodigal Music Player iOS](https://github.com/SpongeBobSun/Prodigal-iOS)：复刻经典iPod的音乐播放器到iOS平台 - [App Store](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)

* :white_check_mark: [Prodigal Music Player Android](https://github.com/SpongeBobSun/Prodigal)：复刻经典iPod的音乐播放器到Android平台 - [Google Play](https://play.google.com/store/apps/details?id=bob.sun.prodigal
)

**Comment by SpongeBobSun** [comment]
不好意思没注意Issue规范，已按要求重新填写

谢谢！

**Comment by 1c7** [comment]
没事，你这个我可能还得稍微改一点点。加进去了会和你说哈

**Comment by 1c7** [comment]
```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8)：开源免费的离线密码管理器

* :white_check_mark: [Prodigal Music Player iOS](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器到iOS平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal-iOS)

* :white_check_mark: [Prodigal Music Player Android](https://play.google.com/store/apps/details?id=bob.sun.prodigal)：复刻经典iPod的音乐播放器到Android平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal)
```

**Comment by 1c7** [comment]
你看看这个格式行不行？因为标题必须是跳到网站 / App。跳到 github 会比较困惑人
（表里的确有几个是跳到 Github 的，但是顶部就马上给了链接，）
相关东西我都放到更多介绍里了。

**Comment by 1c7** [comment]
第一个  password manager 有2个版本，ios 和 Android，这个我知道，但是没法那样写，你可以弄一个博客文章在里面写点东西介绍一下，然后贴到 [更多介绍] 里面，

**Comment by 1c7** [comment]
@SpongeBobSun  海绵宝宝太阳？

**Comment by 1c7** [comment]
我先加进去了~ 要改格式再改~ 
你和我说就行~

**Comment by SpongeBobSun** [comment]
哈哈，不是太阳，我姓孙。。。


```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager iOS] (https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8): iOS上开源免费的离线密码管理器 - [更多介绍](https://github.com/PuffOpenSource/Puff-iOS)

* :white_check_mark: [Puff Password Manager Android] (https://play.google.com/store/apps/details?id=sun.bob.leela): Android上开源免费的离线密码管理器 - [更多介绍](https://github.com/PuffOpenSource/Puff-Android)

* :white_check_mark: [Prodigal Music Player iOS](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器到iOS平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal-iOS)

* :white_check_mark: [Prodigal Music Player Android](https://play.google.com/store/apps/details?id=bob.sun.prodigal)：复刻经典iPod的音乐播放器到Android平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal)
```

#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager iOS] (https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8)：开源免费的离线密码管理器 - [更多介绍](https://github.com/PuffOpenSource/Puff-iOS)

* :white_check_mark: [Puff Password Manager Android] (https://play.google.com/store/apps/details?id=sun.bob.leela)：开源免费的离线密码管理器 - [更多介绍](https://github.com/PuffOpenSource/Puff-Android)

* :white_check_mark: [Prodigal Music Player iOS](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器到iOS平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal-iOS)

* :white_check_mark: [Prodigal Music Player Android](https://play.google.com/store/apps/details?id=bob.sun.prodigal)：复刻经典iPod的音乐播放器到Android平台 - [更多介绍](https://github.com/SpongeBobSun/Prodigal)


---
您看下这个格式可以咩

**Comment by 1c7** [comment]
可以可以

**Comment by SpongeBobSun** [comment]
谢谢～

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/37585657-d2b86a9c-2b94-11e8-8ea2-68e650f8ce13.png)
我再调一点点地方，这里括号好像没写对

**Comment by 1c7** [comment]
没事没事~我刚加进去了~ 我现在改成这个格式

**Comment by SpongeBobSun** [comment]
好的～

**Comment by 1c7** [comment]
能改成2行吗？因为本质上是1个产品，只是2个版本而已。你在更多介绍里面贴上就行了。

**Comment by 1c7** [comment]
我不想听起来特别事儿逼的样子。。就是。。这样比较好一点

**Comment by SpongeBobSun** [comment]
可以的，我改下哈

**Comment by 1c7** [comment]
先临时拿掉了~  待会你改好了加上去。真不好意思，挺耽误你时间的

**Comment by SpongeBobSun** [comment]
```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8): 开源免费的离线密码管理器 - 更多介绍: [iOS](https://github.com/PuffOpenSource/Puff-iOS) [Android](https://github.com/PuffOpenSource/Puff-Android)

* :white_check_mark: [Prodigal Music Player](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器 - 更多介绍: [iOS](https://github.com/SpongeBobSun/Prodigal-iOS)  [Android](https://github.com/SpongeBobSun/Prodigal)
```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8): 开源免费的离线密码管理器 - 更多介绍: [iOS](https://github.com/PuffOpenSource/Puff-iOS) [Android](https://github.com/PuffOpenSource/Puff-Android)

* :white_check_mark: [Prodigal Music Player](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器 - 更多介绍: [iOS](https://github.com/SpongeBobSun/Prodigal-iOS)  [Android](https://github.com/SpongeBobSun/Prodigal)

---
这样可以不～默认链接跳转到App Store，更多介绍分成两个版本

**Comment by 1c7** [comment]
这个。。更多介绍只能是1个链接，不好意思，主要是为了整洁，
也许你可以建多一个 github repo，然后更多介绍里面链接过去，然后里面附上2个版本

**Comment by 1c7** [comment]
多谢理解

**Comment by SpongeBobSun** [comment]
这样啊，好的

**Comment by SpongeBobSun** [comment]
```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8): 开源免费的离线密码管理器 - [更多介绍](https://puffopensource.github.io/)

* :white_check_mark: [Prodigal Music Player](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器 - [更多介绍](http://spongebobsun.github.io/Prodigal/)
```
#### SpongeBobSun - [Github](https://github.com/SpongeBobSun/)
* :white_check_mark: [Puff Password Manager](https://itunes.apple.com/cn/app/puff-password-manager-open-source-free/id1183663532?mt=8): 开源免费的离线密码管理器 - [更多介绍](https://puffopensource.github.io/)

* :white_check_mark: [Prodigal Music Player](https://itunes.apple.com/cn/app/prodigal-music-player/id1231296263?mt=8)：复刻经典iPod的音乐播放器 - [更多介绍](http://spongebobsun.github.io/Prodigal/)

@1c7 ping...
您看下这样可以不咯，抽时间搭了两个简单的landing page

**Comment by 1c7** [comment]
@SpongeBobSun 没问题！ 我加进去！

**Comment by SpongeBobSun** [comment]
蟹蟹～

**Comment by 1c7** [comment]
@SpongeBobSun  加进去了~ 
![image](https://user-images.githubusercontent.com/1804755/37639134-28df6b12-2c4b-11e8-9ee6-3a59a3b120eb.png)
