### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by goodnlp** [1c7/chinese-independent-developer#219]
#### Arxiv Search - [Github](https://github.com/goodnlp/all-you-need-is-arxiv-search)
* :white_check_mark: [Arxiv Search]()： 一个用于追踪各个领域最新Arxiv论文的搜索引擎和浏览网站。目前包含两大功能：(1) 一个网站, 包含各个领域最新文章的检索，和任意时间段的研究趋势的分析；https://www.arxiv.dev 已经上线，包含搜索功能，分领域的论文浏览功能，还有更多数据分析的功能正在开发中。(2) 基于微信搜索获取最新arxiv论文推送。

**Comment by 1c7** [comment]
已加，感谢提交
