### ISSUE TITLE
网站失效

### ISSUE THREAD

**Issue by adhu2018** [1c7/chinese-independent-developer#220]
2019年9月4号添加
arvinxx(杭州) - Github
✅ 多译：一款多源翻译效率工具 - 更多介绍

duoyi.io 已经变成色情网页了

**Comment by 1c7** [comment]
收到

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/6dc1cdefe27d2d9d7e854867289560316e56e612
