### ISSUE TITLE
申请收录：微信小程序-羽毛球助手

### ISSUE THREAD

**Issue by shenpvip** [1c7/chinese-independent-developer#222]
#### shenpvip - [Github](https://github.com/shenpvip)
* :white_check_mark: [羽毛球助手](https://s3.bmp.ovh/imgs/2023/01/09/0ba2aa198f7e8a33.jpg)：一键参与、发起羽毛球活动- [更多介绍](https://github.com/shenpvip)

**Comment by 1c7** [comment]
已添加，感谢提交
