### ISSUE TITLE
miniits(厦门)

### ISSUE THREAD

**Issue by hy4101** [1c7/chinese-independent-developer#233]
BdTab新标签页扩展：这是一个浏览器扩展程序，高度自定义，组件化，跨平台等功能的工具。官网：www.bdtab.cn

**Comment by 1c7** [comment]
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1804755/217541415-6927e3ec-659c-4bf0-a3fc-4028db56acac.png">

已添加。
有个疑问：为啥不支持 https？

**Comment by hy4101** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我会尽快回复你的          谢谢        王琼
