### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by Tuluobo** [1c7/chinese-independent-developer#24]
#### Tuluobo - [Github](https://github.com/Tuluobo)
* :white_check_mark: [玩客钱包](https://github.com/Tuluobo/LKWallet): 迅雷玩客币（改名链克）的非官方查询管理钱包APP。

**Comment by 1c7** [comment]
收到！我看看，没问题就加进去了

**Comment by 1c7** [comment]
@Tuluobo 已添加~ 略做了修改，直接链接到 App 下载地址，而 Github 我放到了更多介绍里

**Comment by 1c7** [comment]
感谢提交！
