### ISSUE TITLE
关于项目列表的日期

### ISSUE THREAD

**Issue by duchengyao** [1c7/chinese-independent-developer#241]
请教项目列表的添加日期有什么作用呢，感觉有点影响阅读>_<

--------

另外，是否可以添加我的项目到“程序员版本”：

#### S1NH - [博客](http://s1nh.org/)
* :white_check_mark: [gpu-based-image-stitching](https://github.com/duchengyao/gpu-based-image-stitching)：一个快速图像拼接算法 -  [介绍1](http://s1nh.org/post/A-survey-on-image-mosaicing-techniques/), [介绍2](http://s1nh.org/post/image-stitching-post-process/)

**Comment by 1c7** [comment]
好的好的

**Comment by 1c7** [comment]
日期更多是判断新鲜度吧，没日期的话读起来感觉差点意思。
主要得有个顺序。

**Comment by 1c7** [comment]
[加上去了](https://github.com/1c7/chinese-independent-developer/commit/a4f7df904c7c652eaf3b408673f91ffbbdd2a9d7)
感谢提交

**Comment by duchengyao** [comment]
原来是这样，好的谢谢^_^
