### ISSUE TITLE
申请收录：减肥小助手

### ISSUE THREAD

**Issue by aizuzi** [1c7/chinese-independent-developer#246]
### aizuzi - [Github](https://github.com/aizuzi) 
* :white_check_mark: [减肥小助手](https://apps.apple.com/cn/app/id1583776291)：减肥期间的小工具，帮助记录体重和卡路里 - [更多介绍](https://ohee.cn/static/download/index.html)

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/4f80d8a0272028916270b8d3ce6f213fc2361301

已添加，感谢提交！
