### ISSUE TITLE
Python学习导航

### ISSUE THREAD

**Issue by forrestcbb** [1c7/chinese-independent-developer#249]
#### CBB - [Github](https://github.com/forrestcbb/AwesomePythonResource)
* :white_check_mark: [Python学习导航](https://www.python1989.com/)：收录各种Python学习资源，帮助每个想学习Python的朋友，在找资源方面，少走弯路。- [更多介绍](https://www.python1989.com/about-us/)

**Comment by 1c7** [comment]
<img width="1335" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/fc927eaf-dd8f-4203-8182-21a84bb6395f">

<img width="1334" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/17c8db46-6d74-4319-8589-ace8e1547158">

感觉价值很低啊。同样是导航站，有的导航站做的很漂亮然后新奇的东西比较多。这个看着不太行。

暂时不收录，意思不大
