### ISSUE TITLE
申请收录：LeaferJS - 绚丽多彩的 HTML5 Canvas 2D 图形渲染引擎

### ISSUE THREAD

**Issue by leaferjs** [1c7/chinese-independent-developer#255]
Leafer(北京) - [Github](https://github.com/leaferjs/ui)
✅ [LeaferJS](https://www.leaferjs.com/)： 绚丽多彩的 HTML5 Canvas 2D 图形渲染引擎， 可结合 AI 绘图、生成界面，能让你拥有瞬间创建100万个图形的超强能力，免费开源、易学易用、场景丰富 - [更多介绍](https://leaferjs.com/ui/blog/2023-06-28.html)

**Comment by 1c7** [comment]
[已添加](https://github.com/1c7/chinese-independent-developer/commit/b5b2e94030444e307ab65a95c21de8298d5887b1) 感谢提交！

**Comment by leaferjs** [comment]
貌似没提交上，被后来合并的代码给挤掉了

**Comment by leaferjs** [comment]
> [已添加](https://github.com/1c7/chinese-independent-developer/commit/b5b2e94030444e307ab65a95c21de8298d5887b1) 感谢提交！
貌似没提交上，被后来合并的代码给挤掉了

**Comment by 1c7** [comment]
<img width="1228" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/da6b80bd-2e23-4ed4-8f18-aacbbe1824e6">


你好，主板面和程序员版面是分开的。您的项目位于程序员版面（请看如上截图）
