### ISSUE TITLE
LeaferJS - 绚丽多彩的 HTML5 Canvas 2D 图形渲染引擎

### ISSUE THREAD

**Issue by leaferjs** [1c7/chinese-independent-developer#257]
您好，我看昨天的没添加上，被其他代码覆盖了，再来申请一下～

Leafer(北京) - [Github](https://github.com/leaferjs/ui)
✅ [LeaferJS](https://www.leaferjs.com/)： 绚丽多彩的 HTML5 Canvas 2D 图形渲染引擎， 可结合 AI 绘图、生成界面，能让你拥有瞬间创建100万个图形的超强能力，免费开源、易学易用、场景丰富 - [更多介绍](https://leaferjs.com/ui/blog/2023-06-28.html)

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/issues/255#issuecomment-1633774397
