### ISSUE TITLE
GSYGithubAPP

### ISSUE THREAD

**Issue by CarGuo** [1c7/chinese-independent-developer#26]
#### CarGuo- [GSYGithubAPP](https://github.com/CarGuo/GSYGithubAPP)
* :white_check_mark: [GSYGithubAPP](https://github.com/CarGuo/GSYGithubAPP): 基于react native开发的高质量的Github客户端。

**Comment by 1c7** [comment]
看到！ 我检查下，没问题了就加进去~

**Comment by 1c7** [comment]
加进去了，
稍微做了点修改，因为这里是着重产品的，就没把 React Native 那句话加进去希望理解
![image](https://user-images.githubusercontent.com/1804755/37580772-6f7c9700-2b80-11e8-9435-987b3cb43ef8.png)

感谢提交！
