### ISSUE TITLE
一点建议，希望能采纳。

### ISSUE THREAD

**Issue by auula** [1c7/chinese-independent-developer#263]
你好，我是最近才发现你这个仓库的，这个是一个很好的仓库，我想我可以提一些建议我们可以把这些独立开发者聚集起来，一起交流产品 IDEA ，或者可以让更多开发者自由组队来做一个完整的产品，我相信交流才是促进国内每个独立开发者发展，希望我们有空可以组织一些这方面的相关活动，谢谢，可以是完整的 WeChat 交流群或者 QQ 群。

**Comment by 1c7** [comment]
您好，之前其实弄过微信群和  QQ 群（群号 678722344） 
https://github.com/1c7/chinese-independent-developer/issues/67

![IMG_6305](https://github.com/1c7/chinese-independent-developer/assets/1804755/6ec114d3-082a-4baf-8b09-06cfb8a6d9fa)


群里聊天频率很低。

另一个社群 https://w2solo.com/ (way to solo) 的活跃度会明显高一些

**Comment by auula** [comment]
OK ，thank ！
