### ISSUE TITLE
增加标准的平台提示

### ISSUE THREAD

**Issue by yige-yigeren** [1c7/chinese-independent-developer#266]
如题，希望能标明IOS / Android / Windows / Linux支持情况，以一种比较统一的形式标注
✅ [妙言](https://github.com/tw93/MiaoYan) （Mac）：轻灵的 Markdown 笔记本伴你写出妙言 
✅ [文曲星记单词](https://apps.apple.com/us/app/%E6%96%87%E6%9B%B2%E6%98%9F%E8%AE%B0%E5%8D%95%E8%AF%8D/id1618265393)（Mac）：灵感来源于古老的文曲星电子辞典，经典复古的单词记忆软件

**Comment by 1c7** [comment]
一个软件**支持什么平台**是第二优先级，
看完产品的`名字` 和 `一句话描述`之后，感兴趣才会点进去看看有没有适合自己的平台。
我不希望这个列表从上到下一眼扫过去全是 Windows Windows iOS iOS，属于视觉障碍，碍眼。

**Comment by 1c7** [comment]
可以理解为什么想要这个标注，但是整个版面文字应该尽可能精简，而不是一堆重复的平台名。
结论：保持现状，不在产品名字后方列举产品支持的全部平台名。

**Comment by 1c7** [comment]
### 2023年7月23号添加
---
#### 五块一 - [Github](https://github.com/WuKaiYi/AI_painter), [Bilibili](https://space.bilibili.com/3430120)
* :white_check_mark: [机画师](https://apps.apple.com/us/app/id1644645946)：(macOS, Windows) 一个基于 Stable Diffusion 的 AI 绘图 App

#### hoochanlon - [Github](https://github.com/hoochanlon), [博客](https://hoochanlon.github.io)
* :white_check_mark: [Nigate](https://github.com/hoochanlon/Free-NTFS-For-Mac)：(macOS) 一款支持苹果芯片的 Free NTFS for Mac 小工具软件

#### Sunrisepeak - [Github](https://github.com/Sunrisepeak), [Bilibili](https://space.bilibili.com/65858958), [知乎](https://www.zhihu.com/people/SPeakShen)
* :white_check_mark: [KHistory](https://github.com/Sunrisepeak/KHistory)：(macOS, Windows, Linux)🔥一个优雅&跨平台的 键盘/🎮手柄按键 检测及历史记录显示工具, 无需安装单可执行文件 (约900kb大小) 即点即用


### 2023年7月22号添加
---
#### Tw93 - [Github](https://github.com/tw93), [Twitter](https://twitter.com/HiTw93), [博客](https://tw93.fun)
* :white_check_mark: [妙言](https://github.com/tw93/MiaoYan)：(macOS, Windows) 轻灵的 Markdown 笔记本伴你写出妙言

### 2023年7月21号添加
---
#### Tan(佛山) - [Github](https://github.com/tans)
* :white_check_mark: [DenoPark](https://denopark.com)：(Web) 打字RPG游戏，可以背单词，记快捷键

### 2023年7月17号添加
---
#### 张土福(上海) - [Github](https://github.com/tufook), [博客](https://tufook.com/)
* :white_check_mark: [Foresee](https://apps.apple.com/cn/app/foresee-predictions-tracker/id6447700092)：iOS App，跟踪你的预测以提升你的判断力

**Comment by 1c7** [comment]
以上是一个例子，如果整个版面都是一堆 （macOS, Windows, Web) 会混乱

**Comment by yige-yigeren** [comment]
我理解了
