### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by Dreamer365** [1c7/chinese-independent-developer#268]
#### Dreamer365 - [Github](https://github.com/Dreamer365/topspeed-image-compressor), [Gitee](https://gitee.com/dreamer365/topspeed-image-compressor)
* :white_check_mark: [极速图片压缩器](https://github.com/Dreamer365/topspeed-image-compressor)：一款速度极快的图片压缩软件

**Comment by 1c7** [comment]
<img width="1352" alt="图片" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/03a966b5-d8a4-4641-9ca3-58ea9bd400c6">
<img width="1351" alt="图片" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/7b24e12e-000f-43d8-a29f-60a288543741">

感谢提交

**Comment by 1c7** [comment]
<img width="843" alt="图片" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/c3325fa6-8bc1-4efa-beee-c1f2dc35d909">
已添加
