### ISSUE TITLE
申请加入

### ISSUE THREAD

**Issue by tangtaoit** [1c7/chinese-independent-developer#269]
申请加入：

:white_check_mark: [唐僧叨叨]()：仿Telegram的自研开源聊天软件 - [更多介绍](https://github.com/TangSengDaoDao/TangSengDaoDaoServer)

**Comment by 1c7** [comment]
<img width="1162" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/67d54c60-0754-42dd-ac9e-af9491ff057a">

https://github.com/1c7/chinese-independent-developer/commit/fd0c08abb91f3fc9e19270d90f0e26c1a5bc1b92

感谢提交，已添加到程序员版面
