### ISSUE TITLE
网站失效

### ISSUE THREAD

**Issue by mougua** [1c7/chinese-independent-developer#273]
[挖线索](https://waxiansuo.com/) 打开是个没有内容的wordpress网站

**Comment by 1c7** [comment]
<img width="1352" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/2077d495-e9c4-4aad-8cbd-76670396e241">
可以复现问题。

我去把挖线索删掉。

**Comment by 1c7** [comment]
已完成操作。感谢告知

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/d0a65e36f171a9bc3eb5d7e77ea0a36350634c8b
