### ISSUE TITLE
[BUG] README.md中的社区投票无法加载

### ISSUE THREAD

**Issue by 2980077544** [1c7/chinese-independent-developer#283]
如图，社区投票那一栏无法加载图片，点进去之后提示内部服务器错误。

![Screenshot_2023-12-30-08-16-52-536_mark via](https://github.com/1c7/chinese-independent-developer/assets/47817223/04d46726-6744-4a44-a914-de8fd02ada6e)

![Screenshot_2023-12-30-08-18-04-523_mark via](https://github.com/1c7/chinese-independent-developer/assets/47817223/288573d0-57e3-4a6a-a543-c92e33f401ab)

**Comment by 1c7** [comment]
感谢反馈，那个网站挂了，我已将图片注释掉了。
