### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by daimakuai** [1c7/chinese-independent-developer#286]
#### 潮汐表表(青岛) - [博客](http://blog.75271.com)
* :white_check_mark: [潮汐表表](http://images.75271.com/wp-content/uploads/2024/01/2024012208223581.jpg)：看潮汐,查天气就在潮汐表表,出行必备小程序 - [更多介绍](https://blog.75271.com/55685.html)

**Comment by 1c7** [comment]
之前不知道为什么遗漏了，总之今天刚加进去，不好意思哈

**Comment by 1c7** [comment]
<img width="957" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/e6aab423-dc03-49e1-b6d2-8f43962a0094">
