### ISSUE TITLE
AI好物——根据一句话推荐商品

### ISSUE THREAD

**Issue by zhugezifang** [1c7/chinese-independent-developer#293]
产品地址：https://www.ai-code.online/

介绍：AI好物是一个好物推荐网站，当你有需求又不知道买什么的时候，可以根据输入内容给你推荐商品

AI好物诞生的背景：https://www.ai-code.online/story

**Comment by 1c7** [comment]
## 加进去了
<img width="1131" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/56155873-bf23-41b1-a7bc-d2306fa04591">

## 开香港的 VPN  用不了。
<img width="1242" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/7e3d1f38-8dfa-46e1-a970-4975af748fcb">

**Comment by zhugezifang** [comment]
已经解决了访问不了这个问题

**Comment by zhugezifang** [comment]
问下是没有收录了吗？

**Comment by 1c7** [comment]
您好，相关讨论请参考
https://github.com/1c7/chinese-independent-developer/issues/295
