### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by jebberwocky** [1c7/chinese-independent-developer#294]
#### Jebberwocky - [Github](https://github.com/jebberwocky)
* :white_check_mark: [我不会说出去](http://chat.colbt.cc/)：匿名心理谘询/宣泄. 之后会加上命理/八字排盘等

**Comment by 1c7** [comment]
<img width="1119" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/268718dd-6e0a-4975-865b-379060e69413">

需要更多改进，目前给人感觉是个练手的产品，不可以保留对话历史，不可以有多个对话。
目前我已加进列表，以后有一定概率从列表里删掉

**Comment by 1c7** [comment]
<img width="1090" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/2e0368ea-5251-488d-b434-bb9b8e8ce8b6">

感觉不够专注，感觉你就是想做一个大杂烩，能实现的功能全部扔进去

**Comment by jebberwocky** [comment]
@1c7 感谢, 之后会不断完善
