### ISSUE TITLE
鱼龙混杂，没有什么质量的东西啊

### ISSUE THREAD

**Issue by brisk21** [1c7/chinese-independent-developer#295]
有些进去简单的几个免费，笑死了

**Comment by 1c7** [comment]
确实，有一些是"练手级"的感觉，我也加进列表里了。
因为感觉是项目的极早期，希望加进去表里后，能给作者本人一定的激励，让他有一点点流量能更有动力去改进。

能谈谈你对哪几个项目的质量特别不满吗？我先记一下，过几个月考虑删掉这些

**Comment by vespercloud** [comment]
> 确实，有一些是"练手级"的感觉，我也加进列表里了。 因为感觉是项目的极早期，希望加进去表里后，能给作者本人一定的激励，让他有一点点流量能更有动力去改进。
> 
> 能谈谈你对哪几个项目的质量特别不满吗？我先记一下，过几个月考虑删掉这些

比如那个诸葛子房，偷开源项目代码改个名字就声称是自己的  https://github.com/liyupi/sql-mother/issues/58  😂

**Comment by 1c7** [comment]
@vespercloud 收到，感谢告知，看完链接内容，总结出的信息是：
1. "诸葛子房"将 "SQL 之母 - 闯关式 SQL 自学网" 的开源代码拿过来，改了个自己的名字，然后部署到 https://xue-sql.online/  
2. 现在  https://xue-sql.online/ 已经下架了原先的内容，换成了别的东西。

**Comment by 1c7** [comment]
<img width="788" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/e681775c-bb88-4121-a125-8a7334445336">

只能说这个人之前犯过错误，但是 "[AI好物](https://www.ai-code.online/)" 这个产品目前还没有具体的争议，我不确定是不是要删掉还是怎么处理。

**Comment by waterlines** [comment]
> <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/1804755/308802897-e681775c-bb88-4121-a125-8a7334445336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjM5NDIsIm5iZiI6MTcwOTI2MzY0MiwicGF0aCI6Ii8xODA0NzU1LzMwODgwMjg5Ny1lNjgxNzc1Yy1iYjg4LTQxMjEtYTEyNS04YTczMzQ0NDUzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDMyNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRkNjQ1MmY1YWRlMjJhNDYzNzY0NzcwYzBkZjhlNjQwMDU0NjAyMjAxNzcxZjY4ZTA3ZDc0OWJlNTYxNGMwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r7qfQFN2SN-7QE6rHq4U3POFZzKsbfZpjOQcICutZEA">
> 只能说这个人之前犯过错误，但是 "[AI好物](https://www.ai-code.online/)" 这个产品目前还没有具体的争议，我不确定是不是要删掉还是怎么处理。

这个怎么看着像这个最佳平替的翻版
https://www.pingti.app/

**Comment by vespercloud** [comment]
> <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/1804755/308802897-e681775c-bb88-4121-a125-8a7334445336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjgzMjUsIm5iZiI6MTcwOTI2ODAyNSwicGF0aCI6Ii8xODA0NzU1LzMwODgwMjg5Ny1lNjgxNzc1Yy1iYjg4LTQxMjEtYTEyNS04YTczMzQ0NDUzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDQ0MDI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjlhODA0NTViYzA4ODY0ODMxYTFkNmFkNDBlNTY5NzY3NDZlNmJjMjlhYzg3MzhmMzA1YzVmNTQ4MjljOGU0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H-jDyl1y46bxYAvGab-BAZIMjxD6ETZJagzVpiI7vY8">
> 只能说这个人之前犯过错误，但是 "[AI好物](https://www.ai-code.online/)" 这个产品目前还没有具体的争议，我不确定是不是要删掉还是怎么处理。

主要是这家伙不认错呀，道歉也没有，最后还是原作者不计较。我个人认为上榜榜单在精不在多，否则和谷歌没啥区别了。可能的话这个项目也可以作为独立开发项目变现，类似阮一峰，hello github那样。

**Comment by vespercloud** [comment]
> > <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/1804755/308802897-e681775c-bb88-4121-a125-8a7334445336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjM5NDIsIm5iZiI6MTcwOTI2MzY0MiwicGF0aCI6Ii8xODA0NzU1LzMwODgwMjg5Ny1lNjgxNzc1Yy1iYjg4LTQxMjEtYTEyNS04YTczMzQ0NDUzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDMyNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRkNjQ1MmY1YWRlMjJhNDYzNzY0NzcwYzBkZjhlNjQwMDU0NjAyMjAxNzcxZjY4ZTA3ZDc0OWJlNTYxNGMwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r7qfQFN2SN-7QE6rHq4U3POFZzKsbfZpjOQcICutZEA">
> > 只能说这个人之前犯过错误，但是 "[AI好物](https://www.ai-code.online/)" 这个产品目前还没有具体的争议，我不确定是不是要删掉还是怎么处理。
> 
> 这个怎么看着像这个最佳平替的翻版 https://www.pingti.app/

还真有点像....

**Comment by 1c7** [comment]
# AI 好物
<img width="1352" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/8ce90fa1-8f3e-49ca-b392-4f526daf74a5">

# 最佳平替
<img width="1352" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/f4cb520e-3b43-4a56-a992-975241e8df1c">

**Comment by 1c7** [comment]
我没时间去看那么多细节研究谁对谁错，既然诸葛子房 1 个产品是抄的+没看到正式道歉，
现有的"AI好物"又和另一个产品很类似，那我先从表里删掉。直到更多信息出现（让我能判断）

https://github.com/1c7/chinese-independent-developer/commit/cb08e38b03946e4bd6062290fbc2f1a0d7fb216a

**Comment by 1c7** [comment]
一周过去了，既然没有新的讨论，我先关掉这个 issue。
后续有新动态可以开新 issue 或者继续在这边留言，都行。

**Comment by zhugezifang** [comment]
> 我没时间去看那么多细节研究谁对谁错，既然诸葛子房 1 个产品是抄的+没看到正式道歉， 现有的"AI好物"又和另一个产品很类似，那我先从表里删掉。直到更多信息出现（让我能判断）
> 
> [cb08e38](https://github.com/1c7/chinese-independent-developer/commit/cb08e38b03946e4bd6062290fbc2f1a0d7fb216a)

这个事情我说下，已经和原作者沟通下线了过了，还是要老有人故意来搞事情 https://web.okjike.com/repost/65d1727d9185c305d1469abd

**Comment by 1c7** [comment]
好的，我这几天找个空闲时间看一下，然后看看要不要加回去

**Comment by zhugezifang** [comment]
> 好的，我这几天找个空闲时间看一下，然后看看要不要加回去

感谢作者哈

**Comment by zhugezifang** [comment]
> > <img alt="image" width="788" src="https://private-user-images.githubusercontent.com/1804755/308802897-e681775c-bb88-4121-a125-8a7334445336.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyNjM5NDIsIm5iZiI6MTcwOTI2MzY0MiwicGF0aCI6Ii8xODA0NzU1LzMwODgwMjg5Ny1lNjgxNzc1Yy1iYjg4LTQxMjEtYTEyNS04YTczMzQ0NDUzMzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDFUMDMyNzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGRkNjQ1MmY1YWRlMjJhNDYzNzY0NzcwYzBkZjhlNjQwMDU0NjAyMjAxNzcxZjY4ZTA3ZDc0OWJlNTYxNGMwNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.r7qfQFN2SN-7QE6rHq4U3POFZzKsbfZpjOQcICutZEA">
> > 只能说这个人之前犯过错误，但是 "[AI好物](https://www.ai-code.online/)" 这个产品目前还没有具体的争议，我不确定是不是要删掉还是怎么处理。
> 
> 这个怎么看着像这个最佳平替的翻版 https://www.pingti.app/

可以看看项目背景，和这个完全不是一个思路哦 https://www.ai-code.online/story

**Comment by 1c7** [comment]
好的，我收到了，最近工作和私人有不少奇奇怪怪的事情，我得找个空隙来弄这个。

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/b5b0823cd15def1bc21d975ef12ab9e0d6ae78f1
已重新加回列表。

理由：之前的纠纷已结束，后续产品不应当受到影响，现加产品进列表种。

**Comment by zhugezifang** [comment]
> [b5b0823](https://github.com/1c7/chinese-independent-developer/commit/b5b0823cd15def1bc21d975ef12ab9e0d6ae78f1) 已重新加回列表。
> 
> 理由：之前的纠纷已结束，后续产品不应当受到影响

感谢作者
