### ISSUE TITLE
申请收录

### ISSUE THREAD

**Issue by huanghanzhilian** [1c7/chinese-independent-developer#304]
#### huanghanzhilian(北京) - [Github](https://github.com/huanghanzhilian), [博客](https://blog.huanghanlian.com/)
* :white_check_mark: [C-Shopping](https://github.com/huanghanzhilian/c-shopping)：c-shopping是一个精美的web电商系统，支持响应式交互，界面优雅，功能丰富，小巧迅速，包含一个电商平台MVP完整功能，具备良好的审美风格与编码设计。（开源）
* :white_check_mark: [C-Shopping-RN APP](https://github.com/huanghanzhilian/c-shopping-rn)：是一个React Native(Expo) 开发的完整App应用，是一个精美的电商购物应用（开源）
* :white_check_mark: [H-BLOG](https://github.com/huanghanzhilian/h-blog)：基于node.js, express.js 开发同时适配Desktop、Tablet、Phone多种设备的 精简博客系统（开源）
* :white_check_mark: [H-Widget](https://github.com/huanghanzhilian/widget)：一个基于原生JavaScript开发的组件库，包含：轮播、标签页、下拉框、对话框等组件（开源）

**Comment by 1c7** [comment]
已加到程序员版面

https://github.com/1c7/chinese-independent-developer/blob/master/README-Programmer-Edition.md

<img width="1205" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/58567d62-7973-4c9e-9392-b8219c99ecc3">
