### ISSUE TITLE
旅行指南与行程计划 App

### ISSUE THREAD

**Issue by LucasChenZQ** [1c7/chinese-independent-developer#305]
#### 旅行计划 App：小旅星 - [Repo 不公开]()
* :white_check_mark: [小旅星 App]()：旅行指南与行程规划的 App，提供众多开箱即用的旅行路线、目的地旅行资讯（完善中），也可以制定自己的行程。可以添加地点、航班、列车到旅行计划中，并且自动为用户预估日程时间安排。如果与朋友一起出行，还可以邀请朋友加入旅行、共同编辑。 - [iOS](https://apps.apple.com/cn/app/id6468434010), [Android](https://static.triplenty.com/xiaolvxing.apk)

![pic](https://github.com/1c7/chinese-independent-developer/assets/11381864/e749141d-8121-4619-b536-b0dfed44734d)

目前正在迅速更新中，预计将加入以下功能：

1. 行程备忘：可以加入旅行相关的笔记、链接、勾选清单、附件等
2. 天气预估：提供旅行期间的天气信息与预警，精准预测
3. 自动推荐：基于已有的行程，自动推荐沿途、后续地点推荐

**Comment by 1c7** [comment]
<img width="1304" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/0faf2d80-e3e1-493a-81e7-ef16f8c99a9e">

已添加，感谢提交。
