### ISSUE TITLE
申请添加

### ISSUE THREAD

**Issue by jkpang** [1c7/chinese-independent-developer#31]
#### jkpang - [Github](https://github.com/jkpang)
* :white_check_mark: [PPHub](https://itunes.apple.com/cn/app/PPHub%20For%20GitHub/id1314212521?mt=8)：一个简洁漂亮的GitHub客户端 - [更多介绍](https://github.com/jkpang/PPHub-Feedback)

**Comment by 1c7** [comment]
收到！

**Comment by 1c7** [comment]
@jkpang 已添加~ 多谢提交！
