### ISSUE TITLE
创想家视频拍摄管理-

### ISSUE THREAD

**Issue by ideasworkcn** [1c7/chinese-independent-developer#337]
#### 创想家视频拍摄管理 提升独立视频制作人创作生产力！ - [vms.ideaswork.cn](https://vms.ideaswork.cn/#/)
* :white_check_mark: [创想家视频拍摄管理](https://vms.ideaswork.cn/#/)：提升独立视频制作人创作生产力！视频项目管理：制作进度、AI 创作、脚本拍摄待办工具库：提词器、语音生成、封面制作、配乐库 - [更多介绍](https://vms.ideaswork.cn/#/)
```

**Comment by 1c7** [comment]
感谢提交，已添加。
