### ISSUE TITLE
Brick Center——可以免费生成乐高设计图的网站

### ISSUE THREAD

**Issue by Q-Sansan** [1c7/chinese-independent-developer#350]
Brick Center

如果您是一位乐高爱好者，热衷与创造各种乐高形象，BrickCenter可以将您的创意，自动生成乐高设计图。我们的AI乐高生成器可以将你的文字转换成定制的乐高套装。轻松地从照片创建你自己的小人偶，如果您觉得乐高头像很酷，BrickCenter也可以将您的自拍图片，生成乐高头像。还可以来网站浏览由爱好者精心制作的独一无二的乐高作品，不妨来看看吧~~~
链接传送门-> https://www.brickcenter.net
了解Brick Center传送门->https://www.bilibili.com/video/BV1VS411c7oG/?vd_source=19c601036963cded73acdb6212ef2365

<img width="1609" alt="lego1" src="https://github.com/1c7/chinese-independent-developer/assets/164138664/099136af-55d2-41ea-87e9-cb75a77551d7">
<img width="1215" alt="lego2" src="https://github.com/1c7/chinese-independent-developer/assets/164138664/68bc752b-36ca-46d3-9c15-fd2b0e217549">

**Comment by 1c7** [comment]
已添加，感谢提交。

**Comment by 1c7** [comment]
<img width="1288" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/6a3969cb-8101-4c05-8956-97d370055bed">
