### ISSUE TITLE
Rap Generator–一款生成说唱歌词和歌曲的免费AI工具

### ISSUE THREAD

**Issue by huhan-123** [1c7/chinese-independent-developer#352]
bairdhh(武汉) - [Github](https://github.com/huhan-123), [官网](https://rapgenerator.net/)
✅ [Rap Generator](https://rapgenerator.net/)：一款生成说唱歌词和歌曲的免费AI工具。Rap Generator为免费生成说唱歌词和歌曲提供了一个全面的平台。用户可以输入提示词，选择情绪，生成符合描述的个性化的歌词，并可以根据歌词选择免费创建两首定制的说唱歌曲。此外，用户可以免费下载和收听人工智能生成的说唱歌曲。我开发这个网站的目的是希望让每一个Rap音乐爱好者都可以轻松地创作自己喜欢的音乐，希望大家喜欢。

**Comment by 1c7** [comment]
已添加，感谢提交。
