### ISSUE TITLE
中国独立开发者项目列表(网页版)

### ISSUE THREAD

**Issue by kisslove** [1c7/chinese-independent-developer#353]
各位开发者：
        你们好，有幸看见“中国独立开发者项目列表”这个项目，有幸中国独立开发者有如此多的好项目，有幸遇见。
        为了更好的展示开发者的项目/产品，为了好的产品获得更多的关注度，也为了凝聚更多开发者的情绪价值。
        因此，基于 @1c7 的 **chinese-independent-developer** 项目基础数据，开发了[中国独立开发者项目列表（网页版）](https://developer.hubing.online/home)，并将此项目源码开源到[chinese-independent-developer-site](https://github.com/kisslove/chinese-independent-developer-site)。
       再次感谢，@1c7 以及此项目贡献者，有幸遇见。

**Comment by 1c7** [comment]
好的，我把你这个项目也加到表里。

**Comment by kisslove** [comment]
@1c7 感谢。

**Comment by 1c7** [comment]
加到列表里了，但是我也特意备注了和我无关，是第三方开发者开发的，**避免读者认为本项目要转型商业化运作**

**Comment by 1c7** [comment]
我先关闭 issue，因为 issue 列表里只留一个 open 的 issue（用于项目提交）

**Comment by kisslove** [comment]
好的

**Comment by 1c7** [comment]
<img width="1512" alt="image" src="https://github.com/1c7/chinese-independent-developer/assets/1804755/2a103ffa-563c-4132-a337-973dc56d3341">
感觉不行啊，点击单个项目小窗口的关闭按钮会卡半天，然后才能真的关掉。

**Comment by kisslove** [comment]
发现这个问题了，会马上修复

**Comment by kisslove** [comment]
已修复，感谢反馈。

**Comment by Subdue0** [comment]
我提个建议，这个项目完全是可以做成线上的第三方应用商店，先以网页版的形式运转，千万不要商业化运营，因为这会导致失去项目初心，就以一种开放免费的形式，做好分类，让用户自己去点赞，让用户自己去挑选优质的应用，也应该按照热度进行列表排名，这样就可以让优秀的应用走出圈，走向市场，面相大众，这也算是功德一件，毕竟孵化出了一款极其优秀的应用。至于后续网站维护问题，我想这个是不用愁的，因为一个优秀的，有热度的项目，压根就不缺乏开发维护的开发者。

**Comment by 1c7** [comment]
> 我提个建议，这个项目完全是可以做成线上的第三方应用商店，先以网页版的形式运转，千万不要商业化运营，因为这会导致失去项目初心，就以一种开放免费的形式，做好分类，让用户自己去点赞，让用户自己去挑选优质的应用，也应该按照热度进行列表排名，这样就可以让优秀的应用走出圈，走向市场，面相大众，这也算是功德一件，毕竟孵化出了一款极其优秀的应用。至于后续网站维护问题，我想这个是不用愁的，因为一个优秀的，有热度的项目，压根就不缺乏开发维护的开发者。

1. 我工作很忙的，我没有兴趣去运作这个玩意，我希望做的是事业，而不是一个"有点浏览量的网站"
2. 我也不喜欢用"功德"这样的词，现在是市场经济，你能用功德买房子交房租吗。
3. "压根就不缺乏开发维护的开发者" 意思就是白嫖人家时间和劳动力喽。

**Comment by Subdue0** [comment]
> > 我提个建议，这个项目完全是可以做成线上的第三方应用商店，先以网页版的形式运转，千万不要商业化运营，因为这会导致失去项目初心，就以一种开放免费的形式，做好分类，让用户自己去点赞，让用户自己去挑选优质的应用，也应该按照热度进行列表排名，这样就可以让优秀的应用走出圈，走向市场，面相大众，这也算是功德一件，毕竟孵化出了一款极其优秀的应用。至于后续网站维护问题，我想这个是不用愁的，因为一个优秀的，有热度的项目，压根就不缺乏开发维护的开发者。
> 
> 1. 我工作很忙的，我没有兴趣去运作这个玩意，我希望做的是事业，而不是一个"有点浏览量的网站"
> 2. 我也不喜欢用"功德"这样的词，现在是市场经济，你能用功德买房子交房租吗。
> 3. "压根就不缺乏开发维护的开发者" 意思就是白嫖人家时间和劳动力喽。
> 
> 友好讨论哈，就事论事，我用词比较直接，不希望引起争论

这个属于开源类的应用商店项目，你说的工作忙，那不是正常的吗，但是开发维护者又不是你一个人。之所以我说的不要商业化运作，不是说不要赚钱，是不希望弄出百度这种竞价排名应用模式，这会直接破坏市场自由竞争规则，捣毁掉项目，至于你说的事业，我想说的是，一个事情只要有热度，有价值，它是不会缺乏变现的机会的，完全可以通过合理的服务模式获取应该得到的项目收益。

**Comment by 1c7** [comment]
你说的有道理，那么下一步是思考什么是合理的"服务模式"。
这是个商业模式问题。

**Comment by Subdue0** [comment]
> 你说的有道理，那么下一步是思考 "什么是合理的服务模式"。 这是个商业模式问题。
> 
> 这个东西说到底是个类 Product Hunt 项目，国内之前有人做过了，好像是 36kr 的 next， 而且至少还有5家类似的产品（比如 "创造者日报"( https://learnku.com/laravel/t/35549) 现在已关闭） 我没有仔细做过市场调查，所以这方面没什么发言权。
> 
> 但他们的投入不小，36kr 还是知名的媒体，他们都做不起来，我想不到我能有什么理由做起来。

获取收益的模式，一定要合理，能形成闭环，这样项目才能长久，不然是一定会凉的。先不要管别人成不成，做自己想做的就好了，项目行不行，很多的时候是看创始人的意念如何。合理的模式会受到众人的推崇支持的。

**Comment by 1c7** [comment]
你讲的东西又大又宽泛，完全无法执行，只是把问题抛给我来解决

**Comment by 1c7** [comment]
这个项目数据都是开源的，你有兴趣你可以自己做，你不用鼓励我去做

**Comment by Subdue0** [comment]
> 你讲的东西又大又宽泛，完全无法执行，只是把问题抛给我来解决

我是有想法，有思路，知道这个东西如何发展才好，但这个事情拍板的是你，我最多是参与者，贡献者，所以我有想法也只能是建议

**Comment by 1c7** [comment]
不，我没有什么拍板的权力，你完全可以把项目做起来然后自己去思考怎么获取流量，不需要任何人的批准或者同意。
我也不关心这些事情，既不反对，也不认同，只是不关心而已。

**Comment by 1c7** [comment]
你完全可以把数据塞到数据库里，然后搭一个网站或者 App。
然后按正常产品的思路去获取流量，去增长，去得到口碑，去发展

**Comment by Subdue0** [comment]
> 你完全可以把数据塞到数据库里，然后搭一个网站或者 App（前车之鉴：36kr next 和创造者日报） 然后按正常产品的思路去获取流量，去增长，去得到口碑，去发展

楼主不是做了我说的吗？没必要重复造轮子，让他去发展就好了。

**Comment by imlinhanchao** [comment]
> 我提个建议，这个项目完全是可以做成线上的第三方应用商店，先以网页版的形式运转，千万不要商业化运营，因为这会导致失去项目初心，就以一种开放免费的形式，做好分类，让用户自己去点赞，让用户自己去挑选优质的应用，也应该按照热度进行列表排名，这样就可以让优秀的应用走出圈，走向市场，面相大众，这也算是功德一件，毕竟孵化出了一款极其优秀的应用。至于后续网站维护问题，我想这个是不用愁的，因为一个优秀的，有热度的项目，压根就不缺乏开发维护的开发者。

你说的这个东西，有人搞过，叫创造者日报。已经凉了。

**Comment by 1c7** [comment]
> > 你完全可以把数据塞到数据库里，然后搭一个网站或者 App（前车之鉴：36kr next 和创造者日报） 然后按正常产品的思路去获取流量，去增长，去得到口碑，去发展
> 
> 楼主不是做了我说的吗？没必要重复造轮子，让他去发展就好了。

好的

**Comment by 1c7** [comment]
还是要说明，尽管讨论有些激烈，但我没有恶意或者其他不好的意思，只是讨论事情而已，观点比较直接，没有带太多修饰词

**Comment by Subdue0** [comment]
> > 我提个建议，这个项目完全是可以做成线上的第三方应用商店，先以网页版的形式运转，千万不要商业化运营，因为这会导致失去项目初心，就以一种开放免费的形式，做好分类，让用户自己去点赞，让用户自己去挑选优质的应用，也应该按照热度进行列表排名，这样就可以让优秀的应用走出圈，走向市场，面相大众，这也算是功德一件，毕竟孵化出了一款极其优秀的应用。至于后续网站维护问题，我想这个是不用愁的，因为一个优秀的，有热度的项目，压根就不缺乏开发维护的开发者。
> 
> 你说的这个东西，有人搞过，叫创造者日报。已经凉了。

这个我没有了解过诶，但是它凉了，不能说代表这个方向不可行，这种项目要想成，也是非常看创作人的这种发展规划是否合理，推广是否得当的。

**Comment by Subdue0** [comment]
> 你说的有道理，那么下一步是思考 "什么是合理的服务模式"。 这是个商业模式问题。
> 
> 这个东西说到底是个 "类 Product Hunt 项目"，国内之前有人做过了，好像是 36kr 的 next， 而且至少还有5家类似的产品（纯粹估算的数字）（比如 "创造者日报"( https://learnku.com/laravel/t/35549) 现在已关闭） 我没有仔细做过市场调查，所以这方面没什么发言权。
> 
> 但他们的投入不小，36kr 还是知名的媒体，他们都做不起来，我想不到我能有什么理由做起来。
> 
> 说白了就是我不愿意把人生接下来的3年5年10年，投在这个事情上

我刚才了解，简单看了一下这几个类似产品，我作为一个普通用户，光看这几个名字就不太想要了解下去了，比如创作者日报，这个名字，给我的感觉就像是看报纸一样，这个报纸内容谁会关心呢？这类产品，如果我去经营，我给的定位是围绕“应用商店”这个主题起一个合理名字，或者说，我就起“我的应用”这个好了。内容的话，就全靠各位独立开发者奋力发展了，给好的应用置顶流量推荐，收益的话，可以留广告应用位，也可以接其他供应商的首页广告，这个是常见的收益模式，也可以在原来自由排名的基础上，再加一个额外的tab页，这个页面就以竞价排名为核心，排名靠前的代表该应用有米有实力，这样的tab页也并不会影响到原有的自由市场竞争，还有很多其他的收益模式，有流量的话，总有办法挣钱。

**Comment by kisslove** [comment]
哈哈，睡一觉起来，发现这个issue竟然引起这么精彩的讨论。
有想法、有思考、有深度，才会有思想碰撞。

在这个项目里面有源源不断的开发者push自己的产品/项目，然而，push之后
- 怎样才能让更多的人**快速检索**到？
- 如何知道什么样的项目/产品是**受欢迎**的?
- 如何知道哪些项目是现在市场**所缺失**的？
...诸如此类问题。
做**中国独立开发者项目列表(网页版)**，这便是我的初衷。
至于说的以后怎么变现、如何商业化运转，这是一个取舍问题：
- 竞价排名？成为像某度那样被许多诟病的产品？
- 广告变形？用户体验如何保障？
.....太多需要考虑的了。
因此，容不得我做太多思考，做一个先行者，做一个实现我初衷的一个产品。毕竟，好的产品才能接受让用户使用，才能在激烈的市场中生存。
最后，不管谁对[网页版](https://developer.hubing.online/)感兴趣，都可以加入进来。最后的最后，再次感谢 @1c7以及项目贡献值提供的数据支撑。

**Comment by Subdue0** [comment]
> 哈哈，睡一觉起来，发现这个issue竟然引起这么精彩的讨论。 有想法、有思考、有深度，才会有思想碰撞。
> 
> 在这个项目里面有源源不断的开发者push自己的产品/项目，然而，push之后
> 
> * 怎样才能让更多的人**快速检索**到？
> * 如何知道什么样的项目/产品是**受欢迎**的?
> * 如何知道哪些项目是现在市场**所缺失**的？
>   ...诸如此类问题。
>   做**中国独立开发者项目列表(网页版)**，这便是我的初衷。
>   至于说的以后怎么变现、如何商业化运转，这是一个取舍问题：
> * 竞价排名？成为像某度那样被许多诟病的产品？
> * 广告变形？用户体验如何保障？
>   .....太多需要考虑的了。
>   因此，容不得我做太多思考，做一个先行者，做一个实现我初衷的一个产品。毕竟，好的产品才能接受让用户使用，才能在激烈的市场中生存。
>   最后，不管谁对[网页版](https://developer.hubing.online/)感兴趣，都可以加入进来。最后的最后，再次感谢 @1c7以及项目贡献值提供的数据支撑。

我不知道这么说，能不能解释清楚。百度的竞价排名恶心是因为打乱了原有的搜索引擎价值信息排名，做独立的竞价排名是合理的，他只是一个类目，不会搞乱原有自由排名。广告也可以同样做到不恶心用户，只是需要额外花很多心思去做广告。

**Comment by kisslove** [comment]
这是一个取舍问题，现在说这些都为时过早。想要变现的基础一定是**流量**，要一直有好的流量的基础一定是产品足够好。所以想法不落地，终究是想法。如果有好的想法，也可以提给网页版，或者加入进来一起见证产品从零到一。

**Comment by Subdue0** [comment]
> 这是一个取舍问题，现在说这些都为时过早。想要变现的基础一定是**流量**，要一直有好的流量的基础一定是产品足够好。所以想法不落地，终究是想法。如果有好的想法，也可以提给网页版，或者加入进来一起见证产品从零到一。

这也是未来的发展前景，你的项目要想有流量，你就要确确实实的，用心在做一款优秀的产品，要实实在在的，投入大量的精力下去，不然你的项目，一定会随着你意愿的消减而灭亡。

**Comment by kisslove** [comment]
我上一个开源项目[前端监控平台](https://github.com/kisslove/web-monitoring)，第一行代码是6年前写的。有为爱发电，也有独立变现。

**Comment by Subdue0** [comment]
> 我上一个开源项目[前端监控平台](https://github.com/kisslove/web-monitoring)，第一行代码是6年前写的。有为爱发电，也有独立变现。

其实，一款优秀的产品，前期，技术是核心，没有好的技术，雏形会很烂，用户会不想用。
