### ISSUE TITLE
小咪影视 是什么开源项目。。

### ISSUE THREAD

**Issue by moke8** [1c7/chinese-independent-developer#358]
RT， github没搜到，广告吗？是否需要注明？

**Comment by imlinhanchao** [comment]
不是开源项目也能添加。

**Comment by 1c7** [comment]
有道理，我今天把 “小咪影视 ”删了吧，因为这类"视频网站"还是不太合适

**Comment by 1c7** [comment]
这个列表更倾向于放"实际的产品"，而不是永久免费的"看视频网站"，
加进列表里是我的工作疏漏
