### ISSUE TITLE
申请收录 - 全王探测

### ISSUE THREAD

**Issue by Subdue0** [1c7/chinese-independent-developer#369]
#### G (广东) - [Github](https://github.com/Subdue0)
* :white_check_mark: [全王探测-直播源搜索神器](https://isus.cc/)：网站的核心是针对特定的区域范围进行 IP 探测，用于挖掘互联网中各种各样的价值 IP，相当于增强版 [fofa](https://fofa.info/)（佛法无边，强无敌）。内置多种黑科技功能：直播源搜索，直播源解析，直播源探测，直播源追踪，也支持非直播源的其他类型的IP查找，比如，漏洞捕获、优选IP、CDN溯源等等 - [更多介绍](https://isus.cc/frontend/about)

**Comment by 1c7** [comment]
好的，加了，文案略有修改。
