### ISSUE TITLE
Trace一个封装QQ+微信聊天记录分析的Windows桌面应用

### ISSUE THREAD

**Issue by yeayee** [1c7/chinese-independent-developer#371]
#### Civilpy(西安) - [Github](https://github.com/yeayee), [博客](https://intumu.com/)
* ✅ : [Trace](https://github.com/yeayee/Trace)：封装QQ+微信聊天记录分析、B站、小红书竞调数据分析、Selenium+谷歌浏览器（准指纹浏览器，不限登录账号数量）

**Comment by 1c7** [comment]
你这介绍我没看明白，能写简单一些吗？
