### ISSUE TITLE
【网站自荐】一个可以为您喜欢的角色或宠物生成迪士尼皮克斯风格海报的网站

### ISSUE THREAD

**Issue by Q-Sansan** [1c7/chinese-independent-developer#375]
PixarAI

链接传送门->https://www.pixarai.com

PixarAI 可让您利用 AI 的力量，为您最喜欢的角色或宠物生成令人惊叹的迪士尼皮克斯风格的海报。只需上传照片，选择风格，几秒钟内即可轻松地获得独特的皮克斯风格的海报。还可以来网站浏览由爱好者精心制作的独一无二的作品，快来看看吧~~~

![P1](https://github.com/1c7/chinese-independent-developer/assets/164138664/e051cb06-6152-49a9-85be-54b7c81707eb)
![P2](https://github.com/1c7/chinese-independent-developer/assets/164138664/bac54eec-9422-46df-93a3-215b0d71b911)
![P3](https://github.com/1c7/chinese-independent-developer/assets/164138664/e985b3d1-46ac-4bcc-86d3-4d5cd05eb022)

**Comment by 1c7** [comment]
感谢提交，已添加。
