### ISSUE TITLE
【开源自荐】亲戚称呼计算器

### ISSUE THREAD

**Issue by mumuy** [1c7/chinese-independent-developer#380]
#### 亲戚称呼计算器
 仓库地址：[https://github.com/mumuy/relationship](https://github.com/mumuy/relationship)
演示地址：[https://passer-by.com/relationship/](https://passer-by.com/relationship/)：

📜介绍
“中国亲戚关系计算器”为你避免了叫错、不会叫亲戚的尴尬，收录了中国亲戚关系称呼大全，只需简单的输入即可完成称呼计算。称呼计算器同时兼容了不同地域的方言叫法，你可以称呼父亲为：“老爸”、“爹地”、“老爷子”等等。让您准确的叫出亲戚称谓，理清亲属之间的亲戚关系，轻松掌握中国式的亲戚关系换算，让你更了解中国文化。
功能支持：
 :white_check_mark: 通过亲戚的关系链计算亲戚称谓；
 :white_check_mark: 通过亲戚称呼寻找对应关系；
 :white_check_mark: 计算两个亲戚之间的对称及合称

**Comment by 1c7** [comment]
感谢提交，已添加
