### ISSUE TITLE
【内容农场-免费软件自荐】

### ISSUE THREAD

**Issue by FrankZhai367** [1c7/chinese-independent-developer#383]
#### Frank(上海) - [Github](https://github.com/FrankZhai367)
* :white_check_mark: [内容农场](http://122.51.11.251:29189/home)：一句话说明(帮助短视频内容生产者提高100倍产量) - [更多介绍](使用aigc，web自动化，赋能内容创作各个环节【自动获取素材】【AIGC文字生成视频】【批量发布多个多平台】，从而节省内容创作者的时间，提高生产力。1.素材获取：获取多个页面里的同一个模块的内容, eg: 获取某up主，所有视频的，标题，介绍，标签
2. aigc短视频制作：使用aigc快速生成短视频内容。
3. 一键发布：简化发布流程，用户可以一次性将多个内容发布到多个平台，节约时间。
4. 流量获取：通过【获取流量】（即：平台用户互赞功能），帮助用户获得更多流量，提升曝光度。)

**Comment by 1c7** [comment]
你这个篇幅太长而且感觉乱七八糟的，一句话介绍必须简短，不能一大堆。

我缩短为下列这样，如果你觉得有改进空间可以提供一份同样简短的介绍，供我复制黏贴

#### Frank(上海) - [Github](https://github.com/FrankZhai367)
* :white_check_mark: [内容农场](http://122.51.11.251:29189/home)：帮助短视频内容生产者提高100倍产量，使用 AIGC，Web自动化，赋能内容创作各个环节

**Comment by 1c7** [comment]
你这个产品到底是干啥的？我没看明白。

## 看起来似乎是
拿人家的视频，切片，可能生成字幕和做个封面图，标题都是自动生成。
人家 1 个小时的视频，到你这里变成  10 个，20 个 1 分钟不到的短视频，然后批量扔到抖音快手B 站。

**Comment by 1c7** [comment]
如果后续这个产品引起争议，我可能会从列表里删掉，目前暂时看不出什么大毛病

**Comment by FrankZhai367** [comment]
> 你这个产品到底是干啥的？我没看明白。 目标用户是谁？谁付费？还是说薅视频平台的羊毛？
> 
> ## 看起来似乎是（如果我的理解有偏差请指正）
> 拿人家的视频，切片，可能生成字幕和做个封面图，标题都是自动生成。 人家 1 个小时的视频，到你这里变成 10 个，20 个 1 分钟不到的短视频，然后批量扔到抖音快手B 站。

现在是基础版免费使用，以后提供高级版年费使用
做的事其实是用批量获取文字内容，然后二创成视频内容。比方说，获取无版权的 段子列表，用aigc批量生成 段子视频，这样就有了一个 段子的自媒体号。

**Comment by FrankZhai367** [comment]
> 如果后续这个产品引起争议，我可能会从列表里删掉，目前暂时看不出什么大毛病

嗯，有争议的部分我是没做的，比方说爬取视频（而是推荐其他海外的软件实现）

**Comment by 1c7** [comment]
好的，感谢回复
