### ISSUE TITLE
work panel

### ISSUE THREAD

**Issue by KEYIERYI** [1c7/chinese-independent-developer#386]
#### 风决子（北京） - [github](https://github.com/KEYIERYI/FengJueZi-DevProcess)
* :white_check_mark: [Work Panel](https://chromewebstore.google.com/detail/work-panel/blomlkfbgepjlmmggfkegbgielelocef?hl=zh-CN&utm_source=ext_sidebar)：可视化时间流逝工作面板，致力于每日高效工作四小时，工作生活平衡，拒绝996文化 - [更多介绍](https://fengjuezi.lihu666.com/)

**Comment by 1c7** [comment]
感谢提交，已添加。
