### ISSUE TITLE
EngineGo：计算机基础教程 状态有误

### ISSUE THREAD

**Issue by cwxyz007** [1c7/chinese-independent-developer#39]
__[EngineGo](https://www.enginego.org/)：计算机基础教程__ 状态为 __完成__，但实际上 __没有完成__

附图：

![image](https://user-images.githubusercontent.com/14226737/37633761-94e809d0-2c2e-11e8-9f56-4bce29ebf626.png)
![image](https://user-images.githubusercontent.com/14226737/37633763-96813b2c-2c2e-11e8-8fba-d56f6db5c6d0.png)

**Comment by 1c7** [comment]
噢，错了，我去修正！

**Comment by 1c7** [comment]
感谢告知，不知道当初我是看漏了还是咋回事，总之非常感谢

**Comment by cwxyz007** [comment]
不用谢。这个列表很 cool ，感谢你分享这个列表~

2018-03-20 12:05 GMT+08:00 Cheng Zheng <notifications@github.com>:

**Comment by 1c7** [comment]
多谢~
