### ISSUE TITLE
【开源自荐】Kestrel-task: tauri构建的windows待办效率管理工具

### ISSUE THREAD

**Issue by kestrela** [1c7/chinese-independent-developer#407]
#### 微芒不朽(长沙) - [Gitee](https://gitee.com/zhanhongzhu/zhanhongzhu), [网站主页](https://kestrel-task.cn)
* :white_check_mark: [微芒计划](https://kestrel-task.cn)：tauri构建的windows待办效率管理工具 - [更多介绍](https://kestrel-task.cn)

**Comment by 1c7** [comment]
已添加，感谢提交

**Comment by 1c7** [comment]
已添加，感谢提交
