### ISSUE TITLE
申请收录-下一本读什么

### ISSUE THREAD

**Issue by seeeeal** [1c7/chinese-independent-developer#409]
#### 下一本读什么 - [Github](https://github.com/seeeeal)
* :white_check_mark: [下一本读什么](https://xiayibendushenme.com/)：汇总优质书单，解决书荒；按照书单主题与名人推荐进行分类，绝大多数图书在豆瓣都属于8.0以上 - [更多介绍](https://xiayibendushenme.com/about)

**Comment by 1c7** [comment]
已添加到列表中，因此关闭本 Issue
