### ISSUE TITLE
【开源自荐】Flux AI Image Generator - 开源的 AI 文生图网站

### ISSUE THREAD

**Issue by virgoone** [1c7/chinese-independent-developer#414]
#### virgoone(上海) - [Github](https://github.com/virgoone), [网站主页](https://blog.douni.one)

* ✅ [Flux AI Image Generator ](https://fluxaipro.art)：开源的基于 fluxai 包含 prompt 翻译优化的文生图网站 - [更多介绍](https://fluxaipro.art)

**Comment by 1c7** [comment]
已添加，感谢提交。
