### ISSUE TITLE
添加项目

### ISSUE THREAD

**Issue by WHMyyds** [1c7/chinese-independent-developer#424]
[Awesome-Iwb](https://github.com/kriastans/Awesome-Iwb)
一体机和电子白板实用软件合集
已上线
*（我不是开发者）*

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/28be46059b9e5b8d99df94ff6e19ae64141fe7a1
感谢提交，现已添加

**Comment by WHMyyds** [comment]
❤️👍
