### ISSUE TITLE
【独立开发者社区】关于创建中国独立开发者社区的想法

### ISSUE THREAD

**Issue by kisslove** [1c7/chinese-independent-developer#426]
嗨喽各位独立开发者，

今年4月发现了“中国独立开发者项目”这个仓库，让我产生很多想法，于是在5月初基于这个项目数据，创建了[中国独立开发者项目（网页版）](https://developer.hubing.online)，如今运营5个多月，整体效果还不错。看着项目库提交来的越来越多的优秀产品，心里无比感慨。这便更加坚定了我要做“中国独立开发者项目”站点的初心：

- 帮助开发者发现并参与到有趣的项目
- 帮助推广优秀的项目
- 促进中国独立开发者社区的交流与合作
      
有如此多的优秀开发者提交如此多的优秀项目，独立开发者的这个群体未来一定会更加欣欣向荣。

然而，仅一个站点还不足以让独立开发者项目得到更多的曝光。要更好的发展下去，一定少不了**人**的这个关键因子。
因此，最近开始组建独立开发者社区，想要更多的人参与进来。形成线上和线下闭环，为我们独立开发者创建一个和谐向上的生态。

所以，我在此，创建了QQ频道，以此作为社区的交流区，欢迎感兴趣的加入进来：
<img src="https://github.com/user-attachments/assets/904252db-e668-4840-91f2-bf2743dfe8f2" width="180" height="280">

最后，再次感谢“中国独立开发者项目”的项目库的组织者 @1c7 ，让我们有机会在这里相聚，愿中国独立开发者们在各个行业的付出都会收获回报，一路发发发。

**Comment by 1c7** [comment]
补充重要信息：为避免困惑路人，kisslove 这个项目与我（本仓库的创建者）无关，没有利益关系，我没有参与，特此说明。

**Comment by 1c7** [comment]
本 issue 保留 5 天后关闭，因为 Issue 列表里只留一个项目提交的 Issue，避免数量多了比较困惑

**Comment by kisslove** [comment]
> 本 issue 保留 5 天后关闭，因为 Issue 列表里只留一个项目提交的 Issue，避免数量多了比较困惑
@1c7 感谢

**Comment by TheWindX** [comment]
我甚至不知道怎样退订，unsubscribe 了也无效，请求从订阅list移除，谢谢

**Comment by 1c7** [comment]
@TheWindX 把 watch 本项目的开关关掉，在 https://github.com/1c7/chinese-independent-developer 的右上角 Star, Watch 的地方
