### ISSUE TITLE
【网站自荐】img2Video——用AI将图片和文本转换成视频

### ISSUE THREAD

**Issue by Q-Sansan** [1c7/chinese-independent-developer#435]
链接传送门->https://img2video.ai/

网站介绍：Img2Video 是一款创新的 AI 驱动工具，使用户能够通过输入文本或上传图像轻松生成短视频。这项先进的 AI 技术提供了一种独特的方法来创建引人入胜的视频内容。我们的人工智能平台非常适合社交媒体，让视频创作变得轻而易举。立即开始创作爆款内容吧！

![I2V](https://github.com/user-attachments/assets/1091b541-c005-4302-ac06-9dc4df0e1f91)

![I2VE](https://github.com/user-attachments/assets/fb1531ac-80ea-44d9-bd8e-76d051a6f92d)

**Comment by 1c7** [comment]
感谢提交，已添加
