### ISSUE TITLE
【软件自荐】个人独立开发的一些小工具软件推荐

### ISSUE THREAD

**Issue by jark006** [1c7/chinese-independent-developer#436]
#### JARK006 - [Github](https://github.com/jark006)

1. [jarkViewer](https://github.com/jark006/jarkViewer)：Windows平台看图软件
1. [FtpServer](https://github.com/jark006/FtpServer)：Windows平台FTP服务器
1. [小天气](https://github.com/jark006/weather_widget)：安卓平台桌面天气小部件

**Comment by 1c7** [comment]
感谢提交，已添加
