### ISSUE TITLE
FileNeatAI 一款可以自动化整理和分类杂乱文件的AI工具

### ISSUE THREAD

**Issue by MrHuZhi** [1c7/chinese-independent-developer#439]
产品网址：
https://fileneatai.com
![文件禅页面](https://github.com/user-attachments/assets/90551a7b-78bb-4954-8d70-912cb99523a6)
工具简介：
在日常的工作和生活中，我们常常会面对电脑中不断积累的杂乱文件，这种混乱往往让人感到焦头烂额。每次偶然想起来整理时，却总是发现这项任务既耗时又费力。为了解决这一痛点，我开发了一款可以自动化整理和分类杂乱文件的AI工具——FileNeatAI，它可以根据文件夹里的文件内容，通过AI自动的将文件进行分类并整理到不同的文件夹中，同时还可以对一些命名不规则的文件进行智能命名，帮助用户轻松、高效地管理文件，提升工作效率。

如何使用：
1. 自动分类杂乱文件 我们日常处理的文件夹中，常常充满了各种各样、不相关的文件，手动整理非常繁琐。FileNeatAI可以自动帮你分类整理这些文件，同时还支持图片文件。使用时，只需将目标文件夹拖入工具界面，点击“整理文件”按钮，软件会根据文件内容智能分析，将属于同一类别的文件归类到相应的文件夹中。整理过程的进度条显示完成后，会生成一个新的output文件夹，里面就是分类好的文件夹。打开每个文件夹，就能轻松查看分类后的文件
![文件整理](https://github.com/user-attachments/assets/688bdaa3-4a7b-492e-a3f5-44348cfe068e)
2. 批量重命名文件 有时候，我们希望将一些杂乱的文件重命名为更规则、易于记忆的名称，但逐一手动重命名非常耗时。这时，FileNeatAI的批量重命名功能就能大显身手。只需将需要重命名的文件拖入工具，点击下一步，AI会自动为文件生成新名称。如果对默认名称不满意，可以点击右侧的“重试”按钮获取新的命名建议。最终点击“确认命名”，文件便会自动完成重命名，过程简便高效。
![重命名](https://github.com/user-attachments/assets/f16d3aff-9ccd-4f28-9044-d3773f44f5c5)
3. 使用本地模型
软件默认使用在线模型，同时也支持本地模型，可以在个人设置里自行设置。
![个人设置默认](https://github.com/user-attachments/assets/6d4cc259-651b-435c-b9d6-a36753a04792)
默认是使用在线AI来读取文件，经过很多人的建议，本地文件的隐私防泄漏是一个比较大的痛点，所以本次更新支持本地模型，而且更重要的是选择本地模型的话，将不限制整理的文件数量！个人推荐ollama3，我测试的时候用的这个，效果还行，如果是中文用户的话，推荐模型是llamafamily/llama3-chinese-8b-instruct:latest, 你也可以使用其他国产的大模型都可以，在网站https://ollama.com/library 这个上面搜索即可。

如何使用本地模型？：
在网站https://ollama.com/ 上下载好客户端后
![ollama3](https://github.com/user-attachments/assets/4d02dddc-6d60-43b6-abd3-7653a5f2bafe)
打开cmd，输入命令
ollama run llamafamily/llama3-chinese-8b-instruct:latest
如果是第一次使用，则会自动下载这个模型，但下载好之后，会变成下面的状态，就表示可以使用了
![cmd](https://github.com/user-attachments/assets/52a5a3a4-a3c2-4ca5-8bcd-142ba2e6a8aa)
但选择本地模型时候，软件需要几项配置，这里如果不是开发者的话请直接使用我下面的配置：
-  API Server 填写 http://localhost:11434/v1/
- API Key 填写 ollama
-  模型名填写：llamafamily/llama3-chinese-8b-instruct:latest
- 模型 选择：本地模型
填写完成之后点击保存即可使用。
![个人设置](https://github.com/user-attachments/assets/a08360d3-1d6a-45d4-97fd-ddad8a5d6120)
适用人群：
FileNeatAI适合广大学生、上班族、白领、文职人员及任何需要使用计算机办公的用户。无论是日常工作还是学习中频繁处理文件的场景，FileNeatAI都能为你提供简便快捷的解决方案

**Comment by 1c7** [comment]
感谢提交，已添加
