### ISSUE TITLE
【网站自荐】请求收录，感谢～

### ISSUE THREAD

**Issue by luyaohwang** [1c7/chinese-independent-developer#445]
Leo - [Github](https://github.com/luyaohwang)

:white_check_mark: [AI塔罗耳语](https://tarotap.com/)：基于AI的在线塔罗占卜平台，提供多位AI塔罗师风格、智能牌阵推荐、每日运势和神谕卡祝福功能
:white_check_mark: [AI雷诺曼占卜](https://lenormand.life/)：专业AI雷诺曼牌在线占卜平台，支持经典大十字牌阵、九宫格及多种主题牌阵，为用户提供精准的事业感情指引

**Comment by 1c7** [comment]
感谢提交，已添加
