### ISSUE TITLE
【网站自荐】帽子云：GitHub Pages / Cloudflare Pages 的国产替代方案，集成化的静态网站快速创建平台。

### ISSUE THREAD

**Issue by joyoyao** [1c7/chinese-independent-developer#461]
#### joyoyao(上海) - [Github](https://github.com/joyoyao)
* :white_check_mark: [帽子云](https://www.maoziyun.com/)：GitHub Pages / Cloudflare Pages 的国产替代方案，集成化的静态网站快速创建平台- [更多介绍](https://www.maoziyun.com/docs/introduction)

**Comment by 1c7** [comment]
感谢提交，已添加
