### ISSUE TITLE
English translation

### ISSUE THREAD

**Issue by DBX12** [1c7/chinese-independent-developer#52]
Dear Maintainer,
could you provide an English translation?
Thank you

**Comment by 1c7** [comment]
@DBX it's possible, but it require quite a bit of work.
I am not sure I have time for this.
I would try my best~ Create a `README-en.md` file and copy&paste&translate the content.

Thanks for suggestion!

**Comment by 1c7** [comment]
@DBX12
I would close this issue for now, if I create English version, I would let you know~
