### ISSUE TITLE
尝试英语翻译

### ISSUE THREAD

**Issue by leon332157** [1c7/chinese-independent-developer#62]
看了issue，虽然不确定有没有老外来看，但是我可以帮助翻译. 还有就是我认为需要找什么微信公众号推广一下。。

**Comment by 1c7** [comment]
@leon332157 挺好啊，你可以翻译之后直接提 PR 就行~
微信公众号这边我。。完全不会做，不知道找谁，不知道怎么做
谢建议~

**Comment by 1c7** [comment]
我有点强迫症想让 issue list 简洁一些，我先关掉这个 issue，要讨论还是可以继续在这里讨论的
