### ISSUE TITLE
加群交流（可选）

### ISSUE THREAD

**Issue by 1c7** [1c7/chinese-independent-developer#67]
## 有4种选择：

- QQ 群：678722344
- Telegram 聊天群:  https://t.me/indiehackercn
- ~~Telegram 广播群:  https://t.me/cn_sideproject  (用来关注最新发布的项目）(坚持不了定期发新信息，不弄了)~~
- 微信群（想加微信群，先加Q群吱一声，因为微信群超100人了必须邀请，不能发二维码，麻烦）

几种方式各有优劣，请选择自己喜欢的加入~

**Comment by xingxingsisi** [comment]
随便点进去一个就看到，中国色那个复制国外网站http://nipponcolors.com

**Comment by 1c7** [comment]
@xingxingsisi  嗯是的，后来有人告诉我了（我才知道是复制）
![image](https://user-images.githubusercontent.com/1804755/47714780-c3904b80-dc78-11e8-8807-b08d5abe215b.png)

我不确定要不要从表里删

**Comment by mengpengfei** [comment]
我自己套界面做的网站 http://www.damagou.top 可以加进去吗

**Comment by 1c7** [comment]
@mengpengfei  类型不太合适，所以不加了。
![image](https://user-images.githubusercontent.com/1804755/66908733-2f142a00-f03e-11e9-989d-21ee88bd7093.png)

![image](https://user-images.githubusercontent.com/1804755/66908753-35a2a180-f03e-11e9-8790-84a742e1a65f.png)
这个算属于灰色产业的东西，说起来是帮助视觉障碍人士，很好的目的，实际上大部分还是拿来做黑色用途

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo参与者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by itiwll** [comment]
Telegram 聊天群链接失效了

**Comment by tangyxgit** [comment]
我也是独立开发者，我也想加入，开发应用目前有小程序（微信搜索：石榴工坊），web网站（fun16.cn）。爬虫短视频分析电脑客户端（https://fun16.cn/#/?t=tool/client）。全是工具类应用。本人持续迭代更新

**Comment by menglike** [comment]
请问 自研的微信小程序 属于查询工具类 可以加入吗？

**Comment by 1c7** [comment]
@menglike 贴个小程序二维码出来看看

**Comment by tangyxgit** [comment]
![tmp-code](https://github.com/1c7/chinese-independent-developer/assets/10821744/493329c1-017c-4b14-9ea2-95fad4eb810e)
网站首页也有二维码
https://fun16.cn/

**Comment by 1c7** [comment]
@tangyxgit 你按现有的格式参照一下，写个介绍语。方便我直接复制黏贴进去。

**Comment by 1c7** [comment]
关闭此 issue，群反正我也不维护，加群没意义。
微信和 QQ 群有个一百来人。
