### ISSUE TITLE
小黄条：能嵌入windows桌面的跨平台todolist

### ISSUE THREAD

**Issue by cg200776** [1c7/chinese-independent-developer#68]
[小黄条]
能嵌入windows桌面的跨平台todolist，手机、PC双向同步。

主页：www.6fcsj.com

For Windows V1.8.8       更新时间：2018-03-12    
https://sm.myapp.com/original/Office/yynote_V1.8.8.exe
For IOS V1.8.5                 更新时间：2017-11-05
https://itunes.apple.com/cn/app/id1175974945?mt=8
For Android V1.8.1         更新时间：2017-10-30
http://a.app.qq.com/o/simple.jsp?pkgname=com.xiaohuangtiao

**Comment by 1c7** [comment]
#### Drinking 
* :white_check_mark: [小黄条](www.6fcsj.com)：能嵌入 Windows 桌面的跨平台 Todolist，手机、PC 双向同步

**Comment by 1c7** [comment]
已添加！感谢提交！如果需要修改说明或者加一个 [了解更多] 
直接和我说就行
