### ISSUE TITLE
China number one

### ISSUE THREAD

**Issue by lapwat** [1c7/chinese-independent-developer#7]

**Comment by 1c7** [comment]
关闭此 issue，因为没有实质内容。

**Comment by dikiaap** [comment]
It's in #1 on Trending page at the moment. As I'm not understand and can't read Chinese lang. GitHub should add Trending page that sorted by countries.

**Comment by 1c7** [comment]
Oh, I didn't know that, 
Hi @dikiaap, this list put all of Chinese Independent Developer's project together, 
These dev working alone(or in a small team of maybe 2 or 3 people) 
Build these App.

The point of this repo is, people want know what other indie-dev is doing.
