### ISSUE TITLE
自己开发的app，看能否入大神眼哈~

### ISSUE THREAD

**Issue by jiangboLee** [1c7/chinese-independent-developer#9]
[Ptoo](https://github.com/jiangboLee/huangpian):一款美图软件哈，已上线
[即时天气](https://github.com/jiangboLee/WeatherWX):微信小程序，不知道符不符合要求哈~
还有2个app,过些时候开源哈~

**Comment by 1c7** [comment]
临时 closed 一下，待会回来处理~ 感谢提交哈~

**Comment by 1c7** [comment]
我在另一个 issue 里看到你提交了，而且我也加进去了，此 issue 永久关闭~
感谢提交！
