### ISSUE TITLE
项目链接已失效

### ISSUE THREAD

**Issue by Cat7373** [1c7/chinese-independent-developer#90]
搜索`brucefeynman`，其所有的项目的链接已无法打开。

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/45730332-9ecda080-bc03-11e8-8e85-d50c05595543.png)

![image](https://user-images.githubusercontent.com/1804755/45730338-a9883580-bc03-11e8-8ac2-f727544f1e45.png)

**Comment by 1c7** [comment]
我去删掉

**Comment by 1c7** [comment]
https://github.com/1c7/chinese-independent-developer/commit/0c1ff4e057acb8bb31080953c005ab34c59f8b15
