### ISSUE TITLE
是否可以标注开发者的所在地？

### ISSUE THREAD

**Issue by leiz-me** [1c7/chinese-independent-developer#91]
这样可以方便联系是否有可能扎堆沟通交流

**Comment by leiz-me** [comment]
有大概的地理位置就好了，例如你我知道是在广州，也关注了好一阵子了😄

**Comment by 1c7** [comment]
@leiz-me 嗯，那也行。那之后有人提交的话，我会顺带问一下提交者在哪个城市。如果提交者愿意透露我就加进去，如果不愿意透露那就算了，非强制。

**Comment by leiz-me** [comment]
是的，自愿就好

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/46592684-b22fa580-caf7-11e8-9a80-36de7722b710.png)
我把模板改了一下。

**Comment by 1c7** [comment]
## 2019-4-11 更新进展
现在写上城市的人还蛮多的。
![image](https://user-images.githubusercontent.com/1804755/55943482-40d4d900-5c79-11e9-9d99-ffc7079dd95d.png)
