### ISSUE TITLE
项目链接失效

### ISSUE THREAD

**Issue by xiaoyun0710** [1c7/chinese-independent-developer#92]
以下两个项目链接失效
![image](https://user-images.githubusercontent.com/44170798/46990395-b1b88f80-d133-11e8-98bd-6af87d7301b1.png)

**Comment by 1c7** [comment]
我试了，不是失效，是翻墙问题。
![image](https://user-images.githubusercontent.com/1804755/46992215-994c7300-d13b-11e8-8071-afc1d219b7fc.png)
![image](https://user-images.githubusercontent.com/1804755/46992221-9baecd00-d13b-11e8-8281-ba1b2c7a3b21.png)
![image](https://user-images.githubusercontent.com/1804755/46992229-a10c1780-d13b-11e8-94ee-cc54580d92db.png)
![image](https://user-images.githubusercontent.com/1804755/46992233-a5d0cb80-d13b-11e8-81c1-09d3f7b2d156.png)

**Comment by xiaoyun0710** [comment]
感谢回复，确认了一下现在正常，应该只是网络问题。

**Comment by 1c7** [comment]
好
