### ISSUE TITLE
在线图片压缩工具，可指定图片大小压缩图片

### ISSUE THREAD

**Issue by WangYuLue** [1c7/chinese-independent-developer#95]
#### WangYuLue(Shanghai) - [Github](https://github.com/WangYuLue/image-conversion)
* :white_check_mark: [image-conversion](http://www.wangyulue.com/assets/image-comversion/example/index.html)：在线图片压缩，可指定图片大小压缩图片 - [更多介绍](http://www.wangyulue.com/2018/12/20/JS%E4%B8%AD%E9%80%9A%E8%BF%87%E6%8C%87%E5%AE%9A%E5%A4%A7%E5%B0%8F%E6%9D%A5%E5%8E%8B%E7%BC%A9%E5%9B%BE%E7%89%87/#more)

**Comment by 1c7** [comment]
看了没啥问题。加进去了~ 感谢提交！

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/50417211-f2353780-085f-11e9-93e9-5712afb2fcd4.png)

![image](https://user-images.githubusercontent.com/1804755/50417217-fa8d7280-085f-11e9-8d3a-7ccbc87c96b9.png)

![image](https://user-images.githubusercontent.com/1804755/50417232-1ee94f00-0860-11e9-9953-5a7913add711.png)
