### ISSUE TITLE
小度涂鸦(Android涂鸦软件)

### ISSUE THREAD

**Issue by nwsuafzq** [1c7/chinese-independent-developer#96]
#### 小度涂鸦(Android涂鸦软件) - [Github](https://github.com/nwsuafzq/duya_doodle)
* :white_check_mark: [小度涂鸦](https://github.com/nwsuafzq/duya_doodle)：一款安卓版的涂鸦软件 - [更多介绍](https://github.com/nwsuafzq/duya_doodle)

**Comment by 1c7** [comment]
![image](https://user-images.githubusercontent.com/1804755/55853273-e2cdc600-5b92-11e9-923c-055f61669bf5.png)
下载安装地址？
